

'use strict';

const i18n = {
    // Mevcut dil
    currentLanguage: localStorage.getItem('testify_language') || 'tr',
    
    // Desteklenen diller
    languages: {
        tr: {
            name: 'Türkçe',
            flag: '🇹🇷',
            adsenseCountry: 'TR'
        },
        en: {
            name: 'English',
            flag: '🇬🇧',
            adsenseCountry: 'US'
        },
        de: {
            name: 'Deutsch',
            flag: '🇩🇪',
            adsenseCountry: 'DE'
        },
        es: {
            name: 'Español',
            flag: '🇪🇸',
            adsenseCountry: 'ES'
        }
    },
    
    // Çeviriler
    translations: {
        // TÜRKÇE
        tr: {
            // Header
            appName: 'Testify',
            appTagline: 'AI Destekli Test Platformu',
            
            // Navigation
            navDashboard: '📊 Dashboard',
            navTest: '📝 Test Çöz',
            navCreate: '➕ Test Oluştur',
            navNotes: '📓 Notlarım',
            navLeaderboard: '🏆 Liderlik',
            navAnalytics: '📈 Analizler',
            navSettings: '⚙️ Ayarlar',
            
            // Dashboard
            dashboardTitle: 'Dashboard',
            statTestsSolved: 'Çözülen Test',
            statSuccessRate: 'Başarı Oranı',
            statTotalQuestions: 'Toplam Soru',
            statAvgTime: 'Ort. Süre',
            recentActivities: 'Son Aktiviteler',
            noActivities: 'Henüz aktivite yok. Test çözerek başla!',
            
            // Test Modes
            testModeTitle: 'Test Modu Seç',
            modePractice: 'Pratik Modu',
            modePracticeDesc: 'Rahatça çalış, hata yap ve öğren',
            modeExam: 'Sınav Modu',
            modeExamDesc: 'Gerçek sınav koşullarında kendinizi test edin',
            modeAI: 'AI Test',
            modeAIDesc: 'AI tarafından oluşturulan özel testler',
            modeCustom: 'Özel Test',
            modeCustomDesc: 'Kendi testini kendin oluştur',
            
            // Quiz
            question: 'Soru',
            of: '/',
            timer: 'Süre',
            previous: '← Önceki',
            next: 'Sonraki →',
            finish: '✓ Bitir',
            
            // Results
            resultsTitle: 'Test Sonuçları',
            yourScore: 'Puanınız',
            correct: 'Doğru',
            wrong: 'Yanlış',
            success: 'Başarı',
            totalTime: 'Toplam Süre',
            review: '📋 Cevapları İncele',
            newTest: '🔄 Yeni Test',
            
            // AI Chat
            aiChatTitle: 'Testify AI',
            aiChatPlaceholder: 'Testify AI\'ya sor...',
            aiSend: 'Gönder',
            
            // Buttons
            btnStart: 'Başla',
            btnCancel: 'İptal',
            btnSave: 'Kaydet',
            btnDelete: 'Sil',
            btnEdit: 'Düzenle',
            btnClose: 'Kapat',
            
            // Messages
            msgLoading: 'Yükleniyor...',
            msgSuccess: 'İşlem başarılı!',
            msgError: 'Bir hata oluştu!',
            msgConfirm: 'Emin misiniz?',
            
            // Ads
            adLabel: 'Sponsorlu',
            adLabelAlt: 'Reklam',
            adSponsoredContent: 'Sponsorlu İçerik'
        },
        
        // ENGLISH
        en: {
            appName: 'Testify',
            appTagline: 'AI-Powered Test Platform',
            
            navDashboard: '📊 Dashboard',
            navTest: '📝 Take Test',
            navCreate: '➕ Create Test',
            navNotes: '📓 My Notes',
            navLeaderboard: '🏆 Leaderboard',
            navAnalytics: '📈 Analytics',
            navSettings: '⚙️ Settings',
            
            dashboardTitle: 'Dashboard',
            statTestsSolved: 'Tests Solved',
            statSuccessRate: 'Success Rate',
            statTotalQuestions: 'Total Questions',
            statAvgTime: 'Avg. Time',
            recentActivities: 'Recent Activities',
            noActivities: 'No activities yet. Start by taking a test!',
            
            testModeTitle: 'Choose Test Mode',
            modePractice: 'Practice Mode',
            modePracticeDesc: 'Learn comfortably, make mistakes and grow',
            modeExam: 'Exam Mode',
            modeExamDesc: 'Test yourself under real exam conditions',
            modeAI: 'AI Test',
            modeAIDesc: 'Custom tests generated by AI',
            modeCustom: 'Custom Test',
            modeCustomDesc: 'Create your own personalized test',
            
            question: 'Question',
            of: 'of',
            timer: 'Time',
            previous: '← Previous',
            next: 'Next →',
            finish: '✓ Finish',
            
            resultsTitle: 'Test Results',
            yourScore: 'Your Score',
            correct: 'Correct',
            wrong: 'Wrong',
            success: 'Success',
            totalTime: 'Total Time',
            review: '📋 Review Answers',
            newTest: '🔄 New Test',
            
            aiChatTitle: 'Testify AI',
            aiChatPlaceholder: 'Ask Testify AI...',
            aiSend: 'Send',
            
            btnStart: 'Start',
            btnCancel: 'Cancel',
            btnSave: 'Save',
            btnDelete: 'Delete',
            btnEdit: 'Edit',
            btnClose: 'Close',
            
            msgLoading: 'Loading...',
            msgSuccess: 'Success!',
            msgError: 'An error occurred!',
            msgConfirm: 'Are you sure?',
            
            adLabel: 'Sponsored',
            adLabelAlt: 'Advertisement',
            adSponsoredContent: 'Sponsored Content'
        },
        
        // DEUTSCH
        de: {
            appName: 'Testify',
            appTagline: 'KI-gestützte Testplattform',
            
            navDashboard: '📊 Dashboard',
            navTest: '📝 Test machen',
            navCreate: '➕ Test erstellen',
            navNotes: '📓 Meine Notizen',
            navLeaderboard: '🏆 Rangliste',
            navAnalytics: '📈 Analysen',
            navSettings: '⚙️ Einstellungen',
            
            dashboardTitle: 'Dashboard',
            statTestsSolved: 'Gelöste Tests',
            statSuccessRate: 'Erfolgsquote',
            statTotalQuestions: 'Gesamtfragen',
            statAvgTime: 'Durchschn. Zeit',
            recentActivities: 'Letzte Aktivitäten',
            noActivities: 'Noch keine Aktivitäten. Starten Sie mit einem Test!',
            
            testModeTitle: 'Testmodus wählen',
            modePractice: 'Übungsmodus',
            modePracticeDesc: 'Lernen Sie bequem, machen Sie Fehler und wachsen Sie',
            modeExam: 'Prüfungsmodus',
            modeExamDesc: 'Testen Sie sich unter echten Prüfungsbedingungen',
            modeAI: 'KI-Test',
            modeAIDesc: 'Von KI generierte benutzerdefinierte Tests',
            modeCustom: 'Benutzerdefinierter Test',
            modeCustomDesc: 'Erstellen Sie Ihren eigenen personalisierten Test',
            
            question: 'Frage',
            of: 'von',
            timer: 'Zeit',
            previous: '← Zurück',
            next: 'Weiter →',
            finish: '✓ Beenden',
            
            resultsTitle: 'Testergebnisse',
            yourScore: 'Ihre Punktzahl',
            correct: 'Richtig',
            wrong: 'Falsch',
            success: 'Erfolg',
            totalTime: 'Gesamtzeit',
            review: '📋 Antworten überprüfen',
            newTest: '🔄 Neuer Test',
            
            aiChatTitle: 'Testify KI',
            aiChatPlaceholder: 'Fragen Sie Testify KI...',
            aiSend: 'Senden',
            
            btnStart: 'Start',
            btnCancel: 'Abbrechen',
            btnSave: 'Speichern',
            btnDelete: 'Löschen',
            btnEdit: 'Bearbeiten',
            btnClose: 'Schließen',
            
            msgLoading: 'Wird geladen...',
            msgSuccess: 'Erfolg!',
            msgError: 'Ein Fehler ist aufgetreten!',
            msgConfirm: 'Sind Sie sicher?',
            
            adLabel: 'Gesponsert',
            adLabelAlt: 'Werbung',
            adSponsoredContent: 'Gesponserter Inhalt'
        },
        
        // ESPAÑOL
        es: {
            appName: 'Testify',
            appTagline: 'Plataforma de Pruebas con IA',
            
            navDashboard: '📊 Panel',
            navTest: '📝 Hacer Prueba',
            navCreate: '➕ Crear Prueba',
            navNotes: '📓 Mis Notas',
            navLeaderboard: '🏆 Clasificación',
            navAnalytics: '📈 Analíticas',
            navSettings: '⚙️ Ajustes',
            
            dashboardTitle: 'Panel de Control',
            statTestsSolved: 'Pruebas Resueltas',
            statSuccessRate: 'Tasa de Éxito',
            statTotalQuestions: 'Preguntas Totales',
            statAvgTime: 'Tiempo Promedio',
            recentActivities: 'Actividades Recientes',
            noActivities: '¡Aún no hay actividades. Comienza haciendo una prueba!',
            
            testModeTitle: 'Elige el Modo de Prueba',
            modePractice: 'Modo Práctica',
            modePracticeDesc: 'Aprende cómodamente, comete errores y crece',
            modeExam: 'Modo Examen',
            modeExamDesc: 'Pruébate bajo condiciones reales de examen',
            modeAI: 'Prueba IA',
            modeAIDesc: 'Pruebas personalizadas generadas por IA',
            modeCustom: 'Prueba Personalizada',
            modeCustomDesc: 'Crea tu propia prueba personalizada',
            
            question: 'Pregunta',
            of: 'de',
            timer: 'Tiempo',
            previous: '← Anterior',
            next: 'Siguiente →',
            finish: '✓ Terminar',
            
            resultsTitle: 'Resultados de la Prueba',
            yourScore: 'Tu Puntuación',
            correct: 'Correctas',
            wrong: 'Incorrectas',
            success: 'Éxito',
            totalTime: 'Tiempo Total',
            review: '📋 Revisar Respuestas',
            newTest: '🔄 Nueva Prueba',
            
            aiChatTitle: 'Testify IA',
            aiChatPlaceholder: 'Pregunta a Testify IA...',
            aiSend: 'Enviar',
            
            btnStart: 'Comenzar',
            btnCancel: 'Cancelar',
            btnSave: 'Guardar',
            btnDelete: 'Eliminar',
            btnEdit: 'Editar',
            btnClose: 'Cerrar',
            
            msgLoading: 'Cargando...',
            msgSuccess: '¡Éxito!',
            msgError: '¡Ocurrió un error!',
            msgConfirm: '¿Estás seguro?',
            
            adLabel: 'Patrocinado',
            adLabelAlt: 'Publicidad',
            adSponsoredContent: 'Contenido Patrocinado'
        }
    },
    
    /**
     * DİL DEĞİŞTİR
     */
    setLanguage(lang) {
        if (!this.languages[lang]) {
            console.error('Desteklenmeyen dil:', lang);
            return;
        }
        
        this.currentLanguage = lang;
        localStorage.setItem('testify_language', lang);
        
        // Sayfayı güncelle
        this.updatePage();
        
        // Reklamları güncelle
        if (window.AdsManager) {
            AdsManager.updateLanguage(lang);
        }
        
        console.log(`🌍 Dil değiştirildi: ${this.languages[lang].name}`);
    },
    
    /**
     * ÇEVİRİ AL
     */
    t(key) {
        return this.translations[this.currentLanguage][key] || key;
    },
    
    /**
     * SAYFAYI GÜNCELLE
     */
    updatePage() {
        // Tüm data-i18n elementlerini güncelle
        document.querySelectorAll('[data-i18n]').forEach(element => {
            const key = element.getAttribute('data-i18n');
            const translation = this.t(key);
            
            if (element.tagName === 'INPUT' || element.tagName === 'TEXTAREA') {
                element.placeholder = translation;
            } else {
                element.textContent = translation;
            }
        });
        
        // HTML lang attribute güncelle
        document.documentElement.lang = this.currentLanguage;
        
        console.log('✅ Sayfa çevirileri güncellendi');
    },
    
    /**
     * DİL SEÇİCİ OLUŞTUR
     */
    createLanguageSelector() {
        const header = document.querySelector('.header-actions');
        if (!header) return;
        
        // Mevcut selector'ı kaldır
        const existing = document.getElementById('languageSelector');
        if (existing) existing.remove();
        
        const selector = document.createElement('div');
        selector.id = 'languageSelector';
        selector.className = 'language-selector';
        
        const currentLang = this.languages[this.currentLanguage];
        
        selector.innerHTML = `
            <button class="language-button" id="langBtn">
                <span class="language-flag">${currentLang.flag}</span>
                <span class="language-name">${currentLang.name}</span>
                <span class="language-arrow">▼</span>
            </button>
            <div class="language-dropdown" id="langDropdown">
                ${Object.entries(this.languages).map(([code, lang]) => `
                    <button class="language-option ${code === this.currentLanguage ? 'active' : ''}" 
                            onclick="i18n.setLanguage('${code}')">
                        <span class="language-flag">${lang.flag}</span>
                        <span class="language-name">${lang.name}</span>
                        ${code === this.currentLanguage ? '<span class="language-check">✓</span>' : ''}
                    </button>
                `).join('')}
            </div>
        `;
        
        // Theme toggle'dan önce ekle
        const themeToggle = header.querySelector('.theme-toggle');
        if (themeToggle) {
            header.insertBefore(selector, themeToggle);
        } else {
            header.appendChild(selector);
        }
        
        // Dropdown toggle
        const btn = selector.querySelector('#langBtn');
        const dropdown = selector.querySelector('#langDropdown');
        
        btn.addEventListener('click', (e) => {
            e.stopPropagation();
            dropdown.classList.toggle('show');
        });
        
        // Dışarı tıklanınca kapat
        document.addEventListener('click', () => {
            dropdown.classList.remove('show');
        });
        
        console.log('✅ Dil seçici oluşturuldu');
    },
    
    /**
     * BAŞLAT
     */
    init() {
        console.log('🌍 i18n başlatılıyor...');
        
        // Dil seçiciyi oluştur
        this.createLanguageSelector();
        
        // Sayfayı güncelle
        this.updatePage();
        
        console.log(`✅ i18n hazır - Dil: ${this.languages[this.currentLanguage].name}`);
    }
};

// Başlat
document.addEventListener('DOMContentLoaded', () => {
    i18n.init();
});

window.i18n = i18n;
