
window.questionBank = [
    // HAFTA 1: Windows, Mac OS, Linux/Pardus, Mobil, Genel Kavramlar
    { 
        q: "Bilgisayarda yapmak istediğimiz işleri donanıma tercüme eden bileşen nedir?", 
        t: "mcq", 
        o: ["İşletim Sistemi", "BIOS", "Donanım Sürücüsü", "Uygulama Yazılımı"],
        a: "İşletim Sistemi",
        difficulty: "easy",
        week: 1,
        topic: "Genel Kavramlar",
        importance: "high",
        explanation: "İşletim sistemi, kullanıcı ile donanım arasındaki köprüdür. Kullanıcının komutlarını donanımın anlayacağı şekilde çevirir."
    },
    { 
        q: "İşletim sistemi bilgisayarın neye benzetilebilir?", 
        t: "mcq", 
        o: ["Trafik Polisi", "Motor", "Yakıt", "Tekerlek"],
        a: "Trafik Polisi",
        difficulty: "easy",
        week: 1,
        topic: "Genel Kavramlar",
        importance: "high",
        explanation: "İşletim sistemi, tüm sistem kaynaklarını koordine eder ve trafiği yönetir, tıpkı bir trafik polisi gibi."
    },
    { 
        q: "İşletim sistemlerinin temel amaçlarından biri bilgisayarın kullanıcılar tarafından kolay kullanılmasını sağlamaktır.", 
        t: "mcq", 
        o: ["Doğru", "Yanlış", "Kısmen Doğru", "Belirsiz"], 
        a: "Doğru",
        difficulty: "easy",
        week: 1,
        topic: "Genel Kavramlar",
        importance: "medium",
        explanation: "İşletim sisteminin temel amaçlarından ilki, bilgisayarın kolay kullanılmasını sağlamaktır."
    },
    { 
        q: "İşletim sistemlerinin temel amaçlarından biri donanım kaynaklarının verimli bir şekilde kullanılmasını sağlamaktır.", 
        t: "mcq", 
        o: ["Doğru", "Yanlış", "Sadece Windows'ta", "Sadece Linux'ta"], 
        a: "Doğru",
        difficulty: "easy",
        week: 1,
        topic: "Genel Kavramlar",
        importance: "high",
        explanation: "İşletim sisteminin temel amaçlarından ikincisi, donanım kaynaklarının verimli kullanılmasını sağlamaktır."
    },
    { 
        q: "Bir bilgisayar sistemi genel olarak dört temel bileşenden oluşur. Bunlardan biri değildir?", 
        t: "mcq", 
        o: ["Kullanıcılar", "Uygulamalar/Programlar", "Donanım Aygıtları", "Ağ Yönlendiricileri"], 
        a: "Ağ Yönlendiricileri",
        difficulty: "medium",
        week: 1,
        topic: "Genel Kavramlar",
        importance: "high",
        explanation: "Dört temel bileşen: Kullanıcılar, Uygulamalar/Programlar, İşletim Sistemi ve Donanım Aygıtlarıdır."
    },
    { 
        q: "Kelime işlemci veya hesap makinası gibi yazılımlar, bir bilgisayar sisteminin hangi temel bileşenine örnektir?", 
        t: "mcq", 
        o: ["Uygulamalar/Programlar", "İşletim Sistemi", "Donanım", "Sürücüler"],
        a: "Uygulamalar/Programlar",
        difficulty: "easy",
        week: 1,
        topic: "Genel Kavramlar",
        importance: "medium",
        explanation: "Kelime işlemci ve hesap makinası gibi yazılımlar, Uygulamalar/Programlar bileşenine örnektir."
    },
    { 
        q: "İşletim sistemi olmadan bilgisayar sadece bir donanım yığınıdır.", 
        t: "mcq", 
        o: ["Doğru", "Yanlış", "Kısmen Doğru", "Sadece eski bilgisayarlarda doğru"], 
        a: "Doğru",
        difficulty: "easy",
        week: 1,
        topic: "Genel Kavramlar",
        importance: "medium",
        explanation: "İşletim sistemi olmadan bilgisayar, hiçbir işlev gösteremeyen bir donanım yığınından ibarettir."
    },
    { 
        q: "Microsoft firması tarafından geliştirilen işletim sistemi hangisidir?", 
        t: "mcq", 
        o: ["Windows", "Mac OS", "Linux", "Unix"],
        a: "Windows",
        difficulty: "easy",
        week: 1,
        topic: "Windows",
        importance: "low"
    },
    { 
        q: "Apple firması tarafından geliştirilen işletim sistemi hangisidir?", 
        t: "mcq", 
        o: ["Mac OS", "Windows", "Linux", "Android"],
        a: "Mac OS",
        difficulty: "easy",
        week: 1,
        topic: "Mac OS",
        importance: "low"
    },
    { 
        q: "Windows'ta işletim sistemini ilk çalıştırdığımızda karşımıza gelen ekrana ne denir?", 
        t: "mcq", 
        o: ["Masaüstü", "Başlat Menüsü", "Görev Çubuğu", "Kontrol Paneli"],
        a: "Masaüstü",
        difficulty: "easy",
        week: 1,
        topic: "Windows",
        importance: "high",
        explanation: "İşletim sistemini ilk çalıştırdığımızda karşımıza gelen ekrana 'Masaüstü' denir."
    },
    { 
        q: "Windows Masaüstünün temel bileşenleri nelerdir?", 
        t: "mcq", 
        o: ["Görev çubuğu, Başlat menüsü, Hızlı erişim menüleri", "Sadece Başlat menüsü", "Sadece simgeler", "Sadece duvar kağıdı"],
        a: "Görev çubuğu, Başlat menüsü, Hızlı erişim menüleri",
        difficulty: "medium",
        week: 1,
        topic: "Windows",
        importance: "medium",
        explanation: "Masaüstünün temel bileşenleri: görev çubuğu, başlat menüsü ve hızlı erişim menüleridir."
    },
    { 
        q: "Hangi işletim sisteminde Başlat Menüsü, o sisteme özel bir öge olarak belirtilmiştir?", 
        t: "mcq", 
        o: ["Windows", "Mac OS", "Linux", "Unix"],
        a: "Windows",
        difficulty: "medium",
        week: 1,
        topic: "Windows",
        importance: "high",
        explanation: "Başlat menüsü Microsoft Windows'a özel bir ögedir."
    },
    { 
        q: "Windows'ta bir dosyayı aynı sürücü altındaki başka bir klasöre 'sürükleyip bırakmak' ne anlama gelir?", 
        t: "mcq", 
        o: ["Dosya bulunduğu yerden silinip yeni konuma yerleştirilir", "Dosya kopyalanır, eski konumunda kalır", "İşlem hata verir", "Dosya kısayolu oluşturulur"], 
        a: "Dosya bulunduğu yerden silinip yeni konuma yerleştirilir",
        difficulty: "hard",
        week: 1,
        topic: "Windows",
        importance: "medium",
        explanation: "Aynı sürücü içinde sürükle-bırak işlemi yapıldığında dosya taşınır (eski konumdan silinir)."
    },
    { 
        q: "Windows'ta bir dosyayı farklı bir sürücüdeki bir klasöre 'sürükleyip bırakmak' ne anlama gelir?", 
        t: "mcq", 
        o: ["Dosya kopyalanır, eski konumunda kalır", "Dosya bulunduğu yerden silinip yeni konuma yerleştirilir", "İşlem hata verir", "Dosyanın sahipliği değiştirilir"], 
        a: "Dosya kopyalanır, eski konumunda kalır",
        difficulty: "hard",
        week: 1,
        topic: "Windows",
        importance: "medium",
        explanation: "Farklı sürücüler arasında sürükle-bırak işlemi yapıldığında dosya kopyalanır, orijinal dosya yerinde kalır."
    },
    { 
        q: "Windows işletim sisteminde dosya ve klasörleri yönetmek için kullanılan araç nedir?", 
        t: "mcq", 
        o: ["Dosya Gezgini", "Kontrol Paneli", "Görev Yöneticisi", "Sistem Ayarları"],
        a: "Dosya Gezgini",
        difficulty: "easy",
        week: 1,
        topic: "Windows",
        importance: "high",
        explanation: "Windows'ta Dosya Gezgini (File Explorer), dosya ve klasörlerin yönetimi için kullanılır."
    },
    { 
        q: "Mac OS masaüstünde, ekranın alt kısmında bulunan özelleştirilebilir uygulamalar alanına ne ad verilir?", 
        t: "mcq", 
        o: ["Dock", "Taskbar", "Panel", "Launcher"],
        a: "Dock",
        difficulty: "easy",
        week: 1,
        topic: "Mac OS",
        importance: "high",
        explanation: "Ekranın alt kısmında kullanıcı tarafından özelleştirilebilen uygulamalar alanına 'dock' denir."
    },
    { 
        q: "Mac OS işletim sisteminin dosya gezginine verilen isim nedir?", 
        t: "mcq", 
        o: ["Finder", "Explorer", "Navigator", "Browser"],
        a: "Finder",
        difficulty: "medium",
        week: 1,
        topic: "Mac OS",
        importance: "high",
        explanation: "Finder, Mac OS işletim sisteminin dosya gezginidir."
    },
    { 
        q: "Mac OS'ta hangi menü bir nevi başlat menüsü görevi görür?", 
        t: "mcq", 
        o: ["Git Menüsü", "Dosya Menüsü", "Düzen Menüsü", "Görünüm Menüsü"],
        a: "Git Menüsü",
        difficulty: "medium",
        week: 1,
        topic: "Mac OS",
        importance: "medium",
        explanation: "Git menüsü, Mac OS'ta bir nevi başlat menüsü görevi görür."
    },
    { 
        q: "Mac OS'ta bilgisayarı kapatmak için bulunan seçeneklerden biri değildir?", 
        t: "mcq", 
        o: ["Ağ Bağlantısını Kes", "Uyu", "Yeniden Başla", "Sistemi Kapat"], 
        a: "Ağ Bağlantısını Kes",
        difficulty: "medium",
        week: 1,
        topic: "Mac OS",
        importance: "medium",
        explanation: "Mac OS'ta kapatma seçenekleri: Uyu, Yeniden Başla, Sistemi Kapat, Kullanıcı Oturumunu Kapat."
    },
    { 
        q: "Linux en basit ifade ile nedir?", 
        t: "mcq", 
        o: ["Özgür bir işletim sistemi çekirdeğidir", "Bir uygulama programıdır", "Bir donanım bileşenidir", "Bir web tarayıcısıdır"],
        a: "Özgür bir işletim sistemi çekirdeğidir",
        difficulty: "medium",
        week: 1,
        topic: "Linux/Pardus",
        importance: "high",
        explanation: "Linux, en basit ifadeyle özgür bir işletim sistemi çekirdeğidir."
    },
    { 
        q: "Linux çekirdeği üzerine geliştirilen işletim sistemlerine ne ad verilir?", 
        t: "mcq", 
        o: ["Linux Dağıtımları", "Linux Eklentileri", "Linux Modülleri", "Linux Paketleri"],
        a: "Linux Dağıtımları",
        difficulty: "medium",
        week: 1,
        topic: "Linux/Pardus",
        importance: "medium",
        explanation: "Linux çekirdeği üzerine geliştirilen işletim sistemlerine 'Linux dağıtımları' adı verilir."
    },
    { 
        q: "Kaynak kodlarının herkes tarafından görülebiliyor, değiştirilebiliyor ve serbestçe dağıtılabiliyor olması, yazılımın hangi özelliğini ifade eder?", 
        t: "mcq", 
        o: ["Açık Kaynak Kodlu", "Kapalı Kaynak Kodlu", "Shareware", "Freeware"],
        a: "Açık Kaynak Kodlu",
        difficulty: "easy",
        week: 1,
        topic: "Linux/Pardus",
        importance: "high",
        explanation: "Kaynak kodlarının görülebilir, değiştirilebilir ve dağıtılabilir olması, 'açık kaynak kodlu' yazılımların özelliğidir."
    },
    { 
        q: "Pardus işletim sistemi ilk kez çalıştırıldığında ekrana gelen bir kerelik çalışan yapılandırma yardımcısının adı nedir?", 
        t: "mcq", 
        o: ["Kaptan", "Yardımcı", "Rehber", "Kurulum"],
        a: "Kaptan",
        difficulty: "medium",
        week: 1,
        topic: "Linux/Pardus",
        importance: "high",
        explanation: "Pardus'ta ilk çalıştırmada 'Kaptan' isimli yapılandırma yardımcısı çalışır."
    },
    { 
        q: "Pardus, hangi kurum bünyesinde geliştirilmeye başlanmıştır?", 
        t: "mcq", 
        o: ["TÜBİTAK", "ASELSAN", "ODTÜ", "Boğaziçi Üniversitesi"],
        a: "TÜBİTAK",
        difficulty: "medium",
        week: 1,
        topic: "Linux/Pardus",
        importance: "medium",
        explanation: "Pardus, TÜBİTAK bünyesinde geliştirilen yerli ve milli işletim sistemidir."
    },
    { 
        q: "Pardus'un ilk sürümü hangi yıl yayınlanmıştır?", 
        t: "mcq", 
        o: ["2005", "2000", "2010", "2015"],
        a: "2005",
        difficulty: "medium",
        week: 1,
        topic: "Linux/Pardus",
        importance: "low",
        explanation: "Pardus'un ilk sürümü 2005 yılında yayınlanmıştır."
    },
    { 
        q: "Windows ve Mac OS gibi işletim sistemleri, geliştirme merkezlerine göre hangi tip işletim sistemleridir?", 
        t: "mcq", 
        o: ["Sahipli", "Açık Kaynak", "Özgür", "Dağıtık"],
        a: "Sahipli",
        difficulty: "medium",
        week: 1,
        topic: "Linux/Pardus",
        importance: "medium",
        explanation: "Windows ve Mac OS gibi işletim sistemleri, firmalara bağlı sahipli işletim sistemleridir."
    },
    { 
        q: "Mobil işletim sistemleri, normal işletim sistemlerine göre nasıl bir yapıdadır?", 
        t: "mcq", 
        o: ["Daha basit", "Daha karmaşık", "Aynı seviyede", "Daha ağır"],
        a: "Daha basit",
        difficulty: "easy",
        week: 1,
        topic: "Mobil İS",
        importance: "medium",
        explanation: "Mobil işletim sistemleri, masaüstü işletim sistemlerine göre daha basit yapıdadır."
    },
    { 
        q: "Android işletim sistemi hangi çekirdek üzerine kurulmuştur?", 
        t: "mcq", 
        o: ["Linux", "Unix", "Windows NT", "BSD"],
        a: "Linux",
        difficulty: "medium",
        week: 1,
        topic: "Mobil İS",
        importance: "high",
        explanation: "Android, Linux çekirdeği üzerine kurulu bir mobil işletim sistemidir."
    },
    { 
        q: "Apple'ın mobil cihazları için geliştirdiği işletim sisteminin adı nedir?", 
        t: "mcq", 
        o: ["iOS", "Android", "Windows Mobile", "Symbian"],
        a: "iOS",
        difficulty: "easy",
        week: 1,
        topic: "Mobil İS",
        importance: "medium",
        explanation: "iOS, Apple tarafından iPhone ve iPad için geliştirilmiş mobil işletim sistemidir."
    },
    { 
        q: "Pardus işletim sisteminde paket yönetimi için kullanılan araç nedir?", 
        t: "mcq", 
        o: ["PiSi", "APT", "YUM", "DNF"],
        a: "PiSi",
        difficulty: "hard",
        week: 1,
        topic: "Linux/Pardus",
        importance: "low",
        explanation: "PiSi (Packages Installed Successfully as Intended), Pardus'un paket yöneticisidir."
    },
    { 
        q: "Linux sistemlerde root kullanıcısının UID (User ID) değeri nedir?", 
        t: "mcq", 
        o: ["0", "1", "-1", "100"],
        a: "0",
        difficulty: "hard",
        week: 1,
        topic: "Linux/Pardus",
        importance: "low",
        explanation: "Root kullanıcısı (sistem yöneticisi) her zaman 0 UID'sine sahiptir."
    },
    { 
        q: "Windows'ta sistem dosyalarının bulunduğu ana dizin hangisidir?", 
        t: "mcq", 
        o: ["C:\\Windows", "C:\\System", "C:\\Program Files", "C:\\Users"],
        a: "C:\\Windows",
        difficulty: "medium",
        week: 1,
        topic: "Windows",
        importance: "low",
        explanation: "Varsayılan olarak Windows sistem dosyaları C:\\Windows dizininde bulunur."
    },
    { 
        q: "Mac OS'un temelini oluşturan UNIX tabanlı işletim sistemi nedir?", 
        t: "mcq", 
        o: ["Darwin", "FreeBSD", "Solaris", "AIX"],
        a: "Darwin",
        difficulty: "hard",
        week: 1,
        topic: "Mac OS",
        importance: "low",
        explanation: "Darwin, Mac OS X'in açık kaynak kodlu UNIX çekirdeğidir."
    },
    { 
        q: "Windows'ta çalışan işlemleri görmek için kullanılan araç nedir?", 
        t: "mcq", 
        o: ["Task Manager", "Control Panel", "System Monitor", "Process Viewer"],
        a: "Task Manager",
        difficulty: "easy",
        week: 1,
        topic: "Windows",
        importance: "low",
        explanation: "Task Manager (Görev Yöneticisi), çalışan işlemleri, CPU ve bellek kullanımını gösterir."
    },
    { 
        q: "Windows'ta kayıt defterini düzenlemek için kullanılan araç nedir?", 
        t: "mcq", 
        o: ["regedit", "msconfig", "services.msc", "gpedit.msc"],
        a: "regedit",
        difficulty: "hard",
        week: 1,
        topic: "Windows",
        importance: "low",
        explanation: "Regedit, Windows kayıt defterini (registry) düzenlemek için kullanılan araçtır."
    },
    { 
        q: "Mac OS'ta terminal uygulamasının adı nedir?", 
        t: "mcq", 
        o: ["Terminal", "Console", "Shell", "Command Prompt"],
        a: "Terminal",
        difficulty: "easy",
        week: 1,
        topic: "Mac OS",
        importance: "low",
        explanation: "Mac OS'ta Terminal uygulaması, komut satırı arayüzü sağlar."
    },
    { 
        q: "Linux'ta dosya izinlerini değiştirmek için kullanılan komut nedir?", 
        t: "mcq", 
        o: ["chmod", "chown", "chgrp", "umask"],
        a: "chmod",
        difficulty: "medium",
        week: 1,
        topic: "Linux/Pardus",
        importance: "medium",
        explanation: "chmod (change mode) komutu, dosya ve dizinlerin erişim izinlerini değiştirir."
    },
    { 
        q: "Windows'ta disk bölümlerini yönetmek için kullanılan araç nedir?", 
        t: "mcq", 
        o: ["Disk Management", "Partition Manager", "Drive Manager", "Volume Control"],
        a: "Disk Management",
        difficulty: "medium",
        week: 1,
        topic: "Windows",
        importance: "low",
        explanation: "Disk Management aracı, disk bölümlerini oluşturma, silme ve yönetme işlemlerini yapar."
    },
    
    // HAFTA 3: Mantıksal Yapı / Fonksiyonlar / Tarihçe
    { 
        q: "İşletim sisteminin temel görevlerinden biri nedir?", 
        t: "mcq", 
        o: ["Donanımı soyutlamak", "Oyun oynamak", "İnternet bağlantısı kurmak", "Video izlemek"],
        a: "Donanımı soyutlamak",
        difficulty: "easy",
        week: 3,
        topic: "Fonksiyonlar",
        importance: "high",
        explanation: "İşletim sisteminin görevleri: Donanımı soyutlamak, kaynakları yönetmek, kolay ortam sağlamak."
    },
    { 
        q: "İşletim sisteminin hangi görevi, kullanıcıların donanım detayları ile ilgilenmesini gereksiz kılar?", 
        t: "mcq", 
        o: ["Donanımı soyutlamak", "Kaynak yönetimi", "Güvenlik sağlamak", "Ağ yönetimi"],
        a: "Donanımı soyutlamak",
        difficulty: "medium",
        week: 3,
        topic: "Fonksiyonlar",
        importance: "high",
        explanation: "Donanım soyutlama sayesinde kullanıcılar donanım detayları ile uğraşmak zorunda kalmaz."
    },
    { 
        q: "CPU, RAM, disk gibi kaynakların adil dağıtımını yapan işletim sistemi görevine ne denir?", 
        t: "mcq", 
        o: ["Kaynak Yönetimi", "Dosya Yönetimi", "Ağ Yönetimi", "Güvenlik Yönetimi"],
        a: "Kaynak Yönetimi",
        difficulty: "easy",
        week: 3,
        topic: "Fonksiyonlar",
        importance: "high",
        explanation: "Kaynak yönetimi, CPU, RAM, disk gibi kaynakların işlemler arasında adil dağıtımını sağlar."
    },
    { 
        q: "1950'lerde kullanılan ve kart delme makineleri ile veri girişinin yapıldığı sistemlere ne ad verilir?", 
        t: "mcq", 
        o: ["Batch Sistemler", "Real-time Sistemler", "Distributed Sistemler", "Cloud Sistemler"],
        a: "Batch Sistemler",
        difficulty: "medium",
        week: 3,
        topic: "İS Tarihi",
        importance: "high",
        explanation: "1950'lerde kart delme makineleri ile batch (toplu işlem) sistemler kullanılırdı."
    },
    { 
        q: "Çoklu programlama ve zaman paylaşımlı sistemlerin doğuşu hangi yılları kapsamaktadır?", 
        t: "mcq", 
        o: ["1960'lar", "1950'ler", "1970'ler", "1980'ler"],
        a: "1960'lar",
        difficulty: "medium",
        week: 3,
        topic: "İS Tarihi",
        importance: "medium",
        explanation: "1960'larda çoklu programlama ve zaman paylaşımlı sistemler geliştirildi."
    },
    { 
        q: "UNIX'in doğuşu hangi yılları kapsamaktadır?", 
        t: "mcq", 
        o: ["1970'ler", "1960'lar", "1980'ler", "1990'lar"],
        a: "1970'ler",
        difficulty: "easy",
        week: 3,
        topic: "İS Tarihi",
        importance: "medium",
        explanation: "UNIX işletim sistemi 1970'lerde geliştirildi."
    },
    { 
        q: "MS-DOS ve kişisel bilgisayarların yaygınlaşması hangi yıllara denk gelmektedir?", 
        t: "mcq", 
        o: ["1980'ler", "1970'ler", "1990'lar", "2000'ler"],
        a: "1980'ler",
        difficulty: "easy",
        week: 3,
        topic: "İS Tarihi",
        importance: "medium",
        explanation: "1980'lerde MS-DOS ve kişisel bilgisayarlar yaygınlaştı."
    },
    { 
        q: "Windows ve grafik arayüzlerin gelişimi hangi yıllarda gerçekleşmiştir?", 
        t: "mcq", 
        o: ["1990'lar", "1980'ler", "2000'ler", "1970'ler"],
        a: "1990'lar",
        difficulty: "easy",
        week: 3,
        topic: "İS Tarihi",
        importance: "low",
        explanation: "1990'larda Windows ve grafik arayüzler gelişim gösterdi."
    },
    { 
        q: "RAM yetersiz kaldığında disk alanının kullanılması hangi bellek yönetim tekniği ile ilgilidir?", 
        t: "mcq", 
        o: ["Sanal Bellek", "Cache Bellek", "ROM", "BIOS"],
        a: "Sanal Bellek",
        difficulty: "easy",
        week: 3,
        topic: "Bellek Yönetimi",
        importance: "high",
        explanation: "Sanal bellek, RAM yetersiz kaldığında disk alanını kullanarak bellek genişletir."
    },
    { 
        q: "Sanal bellekte kullanılan iki temel yöntem Sayfalama (Paging) ve nedir?", 
        t: "mcq", 
        o: ["Segmentasyon", "Swapping", "Caching", "Buffering"],
        a: "Segmentasyon",
        difficulty: "medium",
        week: 3,
        topic: "Bellek Yönetimi",
        importance: "high",
        explanation: "Sanal bellek iki temel yöntem kullanır: Sayfalama (Paging) ve Segmentasyon."
    },
    { 
        q: "Mantıksal adresi fiziksel adrese dönüştüren birime ne denir?", 
        t: "mcq", 
        o: ["MMU", "CPU", "ALU", "CU"],
        a: "MMU",
        difficulty: "hard",
        week: 3,
        topic: "Bellek Yönetimi",
        importance: "high",
        explanation: "MMU (Memory Management Unit), sanal bellek sisteminde mantıksal adresleri fiziksel adreslere çevirir."
    },
    { 
        q: "MMU'nun açılımı nedir?", 
        t: "mcq", 
        o: ["Memory Management Unit", "Memory Module Unit", "Main Memory Unit", "Multi Memory Unit"],
        a: "Memory Management Unit",
        difficulty: "hard",
        week: 3,
        topic: "Bellek Yönetimi",
        importance: "medium",
        explanation: "MMU, Memory Management Unit (Bellek Yönetim Birimi) anlamına gelir."
    },
    { 
        q: "Dosya yönetiminde, kalıcı veri saklama birimine ne ad verilir?", 
        t: "mcq", 
        o: ["Dosya", "RAM", "Cache", "Register"],
        a: "Dosya",
        difficulty: "easy",
        week: 3,
        topic: "Dosya Yönetimi",
        importance: "medium",
        explanation: "Dosya, kalıcı veri saklama birimidir."
    },
    { 
        q: "FAT32, NTFS, ext4 neye örnektir?", 
        t: "mcq", 
        o: ["Dosya Sistemleri", "İşletim Sistemleri", "Donanım Bileşenleri", "Programlama Dilleri"],
        a: "Dosya Sistemleri",
        difficulty: "medium",
        week: 3,
        topic: "Dosya Yönetimi",
        importance: "high",
        explanation: "FAT32, NTFS, ext4 farklı dosya sistemlerine örnektir."
    },
    { 
        q: "FAT32'nin özelliklerinden biri değildir?", 
        t: "mcq", 
        o: ["Gelişmiş güvenlik özellikleri sunar", "Basit bir dosya sistemidir", "Uyumlu bir dosya sistemidir", "Sınırlı özelliklere sahiptir"], 
        a: "Gelişmiş güvenlik özellikleri sunar",
        difficulty: "medium",
        week: 3,
        topic: "Dosya Yönetimi",
        importance: "high",
        explanation: "FAT32 basit ve uyumludur ancak güvenlik özellikleri sınırlıdır. NTFS gelişmiş güvenlik sunar."
    },
    { 
        q: "Linux işletim sistemleri için yaygın olarak kullanılan dosya sistemi nedir?", 
        t: "mcq", 
        o: ["ext4", "NTFS", "FAT32", "HFS+"],
        a: "ext4",
        difficulty: "medium",
        week: 3,
        topic: "Dosya Yönetimi",
        importance: "high",
        explanation: "ext4, Linux sistemlerde yaygın olarak kullanılan dosya sistemidir."
    },
    { 
        q: "Windows'un modern dosya sistemi hangisidir?", 
        t: "mcq", 
        o: ["NTFS", "FAT32", "ext4", "HFS+"],
        a: "NTFS",
        difficulty: "easy",
        week: 3,
        topic: "Dosya Yönetimi",
        importance: "high",
        explanation: "NTFS (New Technology File System), Windows'un modern ve gelişmiş dosya sistemidir."
    },
    { 
        q: "RAID 0'ın avantajı nedir?", 
        t: "mcq", 
        o: ["Hız", "Güvenlik", "Yedekleme", "Düşük maliyet"],
        a: "Hız",
        difficulty: "medium",
        week: 3,
        topic: "Disk Yönetimi",
        importance: "medium",
        explanation: "RAID 0, striping yaparak veri okuma/yazma hızını artırır ancak yedekleme yapmaz."
    },
    { 
        q: "Aynalama (mirroring) yapan RAID teknolojisi hangisidir?", 
        t: "mcq", 
        o: ["RAID 1", "RAID 0", "RAID 5", "RAID 10"],
        a: "RAID 1",
        difficulty: "medium",
        week: 3,
        topic: "Disk Yönetimi",
        importance: "high",
        explanation: "RAID 1, verileri iki diske aynalayarak (mirroring) yedekleme sağlar."
    },
    { 
        q: "RAID teknolojisinin temel amacı nedir?", 
        t: "mcq", 
        o: ["Hem hız hem veri güvenliği sağlamak", "Sadece hız artırmak", "Sadece veri güvenliği sağlamak", "Disk alanından tasarruf etmek"], 
        a: "Hem hız hem veri güvenliği sağlamak",
        difficulty: "medium",
        week: 3,
        topic: "Disk Yönetimi",
        importance: "medium",
        explanation: "RAID teknolojisi, farklı seviyelerde hem performans hem de veri güvenliği sağlamayı amaçlar."
    },
    { 
        q: "Klavye, fare, yazıcı gibi donanımların yönetiminden hangi işletim sistemi bileşeni sorumludur?", 
        t: "mcq", 
        o: ["Giriş/Çıkış Yönetimi", "Bellek Yönetimi", "İşlem Yönetimi", "Dosya Yönetimi"],
        a: "Giriş/Çıkış Yönetimi",
        difficulty: "easy",
        week: 3,
        topic: "G/Ç Yönetimi",
        importance: "medium",
        explanation: "Giriş/Çıkış (I/O) yönetimi, tüm donanım aygıtlarının işletim sistemi tarafından kontrol edilmesini sağlar."
    },
    { 
        q: "Donanım ile işletim sistemi arasındaki arayüzü sağlayan yazılımlara ne denir?", 
        t: "mcq", 
        o: ["Sürücüler (Drivers)", "Firmware", "BIOS", "Uygulamalar"],
        a: "Sürücüler (Drivers)",
        difficulty: "easy",
        week: 3,
        topic: "G/Ç Yönetimi",
        importance: "high",
        explanation: "Sürücüler (drivers), donanım ile işletim sistemi arasında iletişim sağlar."
    },
    { 
        q: "İşletim sisteminin, kullanıcıların ve işlemlerin kaynaklara erişimini kontrol etme görevine ne denir?", 
        t: "mcq", 
        o: ["Güvenlik ve Koruma", "Kaynak Yönetimi", "İşlem Yönetimi", "Bellek Yönetimi"],
        a: "Güvenlik ve Koruma",
        difficulty: "medium",
        week: 3,
        topic: "Güvenlik",
        importance: "high",
        explanation: "İşletim sistemi, güvenlik ve koruma mekanizmaları ile kaynaklara erişimi kontrol eder."
    },
    { 
        q: "Bir kullanıcının sisteme giriş yaparken kimliğinin doğrulanması işlemine ne denir?", 
        t: "mcq", 
        o: ["Kimlik Doğrulama (Authentication)", "Yetkilendirme (Authorization)", "Şifreleme (Encryption)", "Denetim (Auditing)"],
        a: "Kimlik Doğrulama (Authentication)",
        difficulty: "easy",
        week: 3,
        topic: "Güvenlik",
        importance: "high",
        explanation: "Kimlik doğrulama (authentication), kullanıcının kim olduğunu doğrulama işlemidir."
    },
    { 
        q: "İşletim sisteminin kaynak yönetimi görevlerinden biri değildir?", 
        t: "mcq", 
        o: ["Kullanıcı arayüzü tasarlamak", "CPU zamanını dağıtmak", "Bellek tahsis etmek", "Dosya sistemini yönetmek"], 
        a: "Kullanıcı arayüzü tasarlamak",
        difficulty: "medium",
        week: 3,
        topic: "Fonksiyonlar",
        importance: "medium",
        explanation: "Kaynak yönetimi CPU, bellek, disk gibi donanım kaynaklarının yönetimini içerir; arayüz tasarımı kullanıcı deneyimi ile ilgilidir."
    },
    { 
        q: "İşletim sisteminin donanım ve yazılım arasındaki konumunu belirten kavram nedir?", 
        t: "mcq", 
        o: ["Ara Katman", "Üst Katman", "Alt Katman", "Yan Katman"],
        a: "Ara Katman",
        difficulty: "medium",
        week: 3,
        topic: "Fonksiyonlar",
        importance: "high",
        explanation: "İşletim sistemi, kullanıcı/uygulama ile donanım arasında ara katman (middleware) görevi görür."
    },
    { 
        q: "Bir dosya sisteminde dizin yapısının en üst noktasına ne denir?", 
        t: "mcq", 
        o: ["Root", "Home", "User", "System"],
        a: "Root",
        difficulty: "easy",
        week: 3,
        topic: "Dosya Yönetimi",
        importance: "medium",
        explanation: "Root dizini, dosya sisteminin en üst seviyesidir (Linux'ta /, Windows'ta C:\\)."
    },
    { 
        q: "Sanal bellek kullanıldığında diskte kullanılan alana ne ad verilir?", 
        t: "mcq", 
        o: ["Swap", "Cache", "Buffer", "Partition"],
        a: "Swap",
        difficulty: "medium",
        week: 3,
        topic: "Bellek Yönetimi",
        importance: "high",
        explanation: "Swap alanı, RAM yetersiz kaldığında diskte kullanılan sanal bellek alanıdır."
    },
    { 
        q: "Çok kullanıcılı sistemlerde kullanıcı kimlik doğrulaması yapan işletim sistemi bileşeni nedir?", 
        t: "mcq", 
        o: ["Authentication system", "Authorization system", "Encryption system", "Firewall"],
        a: "Authentication system",
        difficulty: "medium",
        week: 3,
        topic: "Güvenlik",
        importance: "high",
        explanation: "Authentication system, kullanıcıların kimlik doğrulamasını yaparak sisteme erişimi kontrol eder."
    },
    { 
        q: "İşletim sisteminin boot (açılış) sürecinde ilk çalışan program nedir?", 
        t: "mcq", 
        o: ["Bootloader", "Kernel", "Shell", "BIOS"],
        a: "Bootloader",
        difficulty: "medium",
        week: 3,
        topic: "İS Tarihi",
        importance: "low",
        explanation: "Bootloader, bilgisayar açılırken işletim sistemini belleğe yükleyen ilk programdır."
    },
    
    // HAFTA 4: İS Katmanları, Çekirdek, Sistem Çağrıları
    { 
        q: "Bir işletim sisteminin yazılım tasarımında ele alınması gereken iki önemli konudan biri Performans, diğeri nedir?", 
        t: "mcq", 
        o: ["Kaynakların özel kullanımı", "Kullanıcı arayüzü", "Fiyat", "Boyut"],
        a: "Kaynakların özel kullanımı",
        difficulty: "medium",
        week: 4,
        topic: "Genel Kavramlar",
        importance: "high",
        explanation: "İşletim sistemi tasarımında iki önemli konu: Performans ve Kaynakların özel kullanımı (yalıtım/koruma)."
    },
    { 
        q: "İşlemcinin, işletim sisteminin kodlarını çalıştırmaya başladığı yetkili moda ne ad verilir?", 
        t: "mcq", 
        o: ["Supervisor Mod", "User Mod", "Kernel Mod", "System Mod"],
        a: "Supervisor Mod",
        difficulty: "medium",
        week: 4,
        topic: "Çekirdek",
        importance: "high",
        explanation: "Supervisor mod (veya kernel mod), işletim sisteminin tüm kaynaklara erişebildiği yetkili çalışma modudur."
    },
    { 
        q: "Kullanıcı modundaki bir işlemin işletim sistemini çağırdığında, işlemcinin hemen supervisor moda geçmesine ne denir?", 
        t: "mcq", 
        o: ["Sistem Çağrısı", "Kesme", "Tuzak", "Hata"],
        a: "Sistem Çağrısı",
        difficulty: "medium",
        week: 4,
        topic: "Sistem Çağrıları",
        importance: "high",
        explanation: "Sistem çağrısı (system call), kullanıcı modundan kernel moduna geçişi sağlar."
    },
    { 
        q: "İşlemcide, bir programın çalışma yeteneğini gösteren bite ne denir?", 
        t: "mcq", 
        o: ["Mod Biti", "Status Biti", "Flag Biti", "Control Biti"],
        a: "Mod Biti",
        difficulty: "medium",
        week: 4,
        topic: "Çekirdek",
        importance: "high",
        explanation: "Mod biti, programın kullanıcı modunda mı yoksa kernel modunda mı çalıştığını belirler."
    },
    { 
        q: "Mod biti (mode bit) hangi değeri aldığında 'supervisor (kernel) mod'da çalışıldığı anlaşılır?", 
        t: "mcq", 
        o: ["0", "1", "2", "3"],
        a: "0",
        difficulty: "medium",
        week: 4,
        topic: "Çekirdek",
        importance: "high",
        explanation: "Mod biti 0 ise supervisor (kernel) modu, 1 ise kullanıcı modudur."
    },
    { 
        q: "İşletim sistemi programları hangi modda çalışır?", 
        t: "mcq", 
        o: ["Supervisor Mod", "User Mod", "Guest Mod", "Safe Mod"],
        a: "Supervisor Mod",
        difficulty: "medium",
        week: 4,
        topic: "Çekirdek",
        importance: "high",
        explanation: "İşletim sistemi programları, tüm kaynaklara erişebilmek için supervisor modda çalışır."
    },
    { 
        q: "İşletim sistemi ve işlemler arasında bir arayüz görevi gören, genellikle Assembly dili komutları şeklinde olan yapı nedir?", 
        t: "mcq", 
        o: ["Sistem Çağrıları", "Kütüphaneler", "Sürücüler", "API"],
        a: "Sistem Çağrıları",
        difficulty: "hard",
        week: 4,
        topic: "Sistem Çağrıları",
        importance: "high",
        explanation: "Sistem çağrıları, işlemler ile işletim sistemi arasında düşük seviyeli arayüz sağlar."
    },
    { 
        q: "Microsoft Windows, sistem çağrılarını hangi API ile gerçekleştirmektedir?", 
        t: "mcq", 
        o: ["Win32 API", "POSIX API", "Java API", ".NET API"],
        a: "Win32 API",
        difficulty: "hard",
        week: 4,
        topic: "Sistem Çağrıları",
        importance: "medium",
        explanation: "Microsoft Windows, sistem çağrılarını Win32 API üzerinden gerçekleştirir."
    },
    { 
        q: "UNIX/Linux sistemlerinde sistem çağrıları hangi dilde yazılmıştır?", 
        t: "mcq", 
        o: ["C", "Assembly", "Java", "Python"],
        a: "C",
        difficulty: "medium",
        week: 4,
        topic: "Sistem Çağrıları",
        importance: "medium",
        explanation: "UNIX/Linux sistem çağrıları genellikle C dili ile yazılmıştır."
    },
    { 
        q: "Dosya okuma/yazma, işlem oluşturma gibi işlemler hangi mekanizma ile yapılır?", 
        t: "mcq", 
        o: ["Sistem Çağrıları", "Kütüphaneler", "Makrolar", "Fonksiyonlar"],
        a: "Sistem Çağrıları",
        difficulty: "medium",
        week: 4,
        topic: "Sistem Çağrıları",
        importance: "high",
        explanation: "Sistem çağrıları, dosya işlemleri, işlem yönetimi gibi işletim sistemi hizmetlerine erişim sağlar."
    },
    { 
        q: "Word, Excel gibi kullanıcı tarafından kullanılan her tür program, işletim sistemi katmanlarının hangi seviyesinde yer alır?", 
        t: "mcq", 
        o: ["Uygulama Katmanı", "Çekirdek Katmanı", "Donanım Katmanı", "Sistem Katmanı"],
        a: "Uygulama Katmanı",
        difficulty: "easy",
        week: 4,
        topic: "Katmanlar",
        importance: "medium",
        explanation: "Uygulama Katmanı, kullanıcıların doğrudan kullandığı programların bulunduğu en üst katmandır."
    },
    { 
        q: "İşletim sisteminin kalbi olarak adlandırılan ve tüm sistem kaynaklarını yöneten katman hangisidir?", 
        t: "mcq", 
        o: ["Çekirdek (Kernel)", "Shell", "GUI", "API"],
        a: "Çekirdek (Kernel)",
        difficulty: "medium",
        week: 4,
        topic: "Çekirdek",
        importance: "high",
        explanation: "Çekirdek (kernel), işletim sisteminin kalbi olarak tüm sistem kaynaklarını yönetir."
    },
    { 
        q: "Aşağıdakilerden hangisi bir çekirdek türü değildir?", 
        t: "mcq", 
        o: ["Supervisor Çekirdek", "Monolitik", "Mikrokernel", "Hibrid Çekirdek"], 
        a: "Supervisor Çekirdek",
        difficulty: "medium",
        week: 4,
        topic: "Çekirdek",
        importance: "medium",
        explanation: "Çekirdek türleri: Monolitik, Mikrokernel ve Hibrid çekirdektir."
    },
    { 
        q: "Tüm yazılımlar ve sürücülerin işletim sistemi çekirdeğinde yer aldığı çekirdek tipine ne denir?", 
        t: "mcq", 
        o: ["Monolitik Çekirdek", "Mikrokernel", "Hibrid Çekirdek", "Nano Çekirdek"],
        a: "Monolitik Çekirdek",
        difficulty: "hard",
        week: 4,
        topic: "Çekirdek",
        importance: "high",
        explanation: "Monolitik çekirdeklerde tüm sistem servisleri çekirdek içindedir. Hızlıdır ama bir hata tüm sistemi etkileyebilir."
    },
    { 
        q: "Unix, ne tür bir çekirdeğe örnektir?", 
        t: "mcq", 
        o: ["Monolitik", "Mikrokernel", "Hibrid", "Nano"],
        a: "Monolitik",
        difficulty: "medium",
        week: 4,
        topic: "Çekirdek",
        importance: "medium",
        explanation: "Unix, monolitik çekirdek yapısına sahip bir işletim sistemidir."
    },
    { 
        q: "Sadece en önemli işletim sistemi fonksiyonlarının bulunduğu küçük boyutlu çekirdeklere ne denir?", 
        t: "mcq", 
        o: ["Mikrokernel", "Monolitik Çekirdek", "Hibrid Çekirdek", "Makrokernel"],
        a: "Mikrokernel",
        difficulty: "hard",
        week: 4,
        topic: "Çekirdek",
        importance: "high",
        explanation: "Mikrokernel (microkernel), sadece temel işletim sistemi fonksiyonlarını içeren minimal çekirdek yapısıdır."
    },
    { 
        q: "Mikrokernellerde, sürücüler ve dosya sistemleri çekirdeğin dışında nasıl çalışır?", 
        t: "mcq", 
        o: ["Kullanıcı seviyesinde", "Kernel seviyesinde", "Donanım seviyesinde", "Firmware seviyesinde"],
        a: "Kullanıcı seviyesinde",
        difficulty: "hard",
        week: 4,
        topic: "Çekirdek",
        importance: "medium",
        explanation: "Mikrokernellerde birçok servis kullanıcı seviyesinde çalışır, bu da daha güvenli ama daha yavaştır."
    },
    { 
        q: "Monolitik ve mikrokernel yapılarının avantajlarını birleştiren çekirdek tipine ne denir?", 
        t: "mcq", 
        o: ["Hibrid Çekirdek", "Super Çekirdek", "Mega Çekirdek", "Dual Çekirdek"],
        a: "Hibrid Çekirdek",
        difficulty: "medium",
        week: 4,
        topic: "Çekirdek",
        importance: "medium",
        explanation: "Hibrid çekirdekler, monolitik ve mikrokernel yaklaşımlarının avantajlarını birleştirir."
    },
    { 
        q: "Windows NT mimarisinde donanım detaylarının soyutlanmasını sağlayan katman nedir?", 
        t: "mcq", 
        o: ["HAL", "Executive", "Kernel", "GUI"],
        a: "HAL",
        difficulty: "hard",
        week: 4,
        topic: "Katmanlar",
        importance: "high",
        explanation: "HAL (Hardware Abstraction Layer), donanım detaylarını soyutlayarak işletim sisteminin taşınabilirliğini artırır."
    },
    { 
        q: "HAL'in açılımı nedir?", 
        t: "mcq", 
        o: ["Hardware Abstraction Layer", "High Access Level", "Hardware Application Layer", "Host Abstraction Level"],
        a: "Hardware Abstraction Layer",
        difficulty: "hard",
        week: 4,
        topic: "Katmanlar",
        importance: "medium",
        explanation: "HAL, Hardware Abstraction Layer (Donanım Soyutlama Katmanı) anlamına gelir."
    },
    { 
        q: "Windows'ta çekirdek modu ve kullanıcı modu arasındaki iletişimi hangi katman sağlar?", 
        t: "mcq", 
        o: ["Executive", "HAL", "Kernel", "Shell"],
        a: "Executive",
        difficulty: "hard",
        week: 4,
        topic: "Katmanlar",
        importance: "medium",
        explanation: "Executive katmanı, Windows'ta üst düzey sistem hizmetlerini sağlar."
    },
    { 
        q: "Donanım tarafından oluşturulan ve işlemciyi durduran sinyallere ne denir?", 
        t: "mcq", 
        o: ["Kesme (Interrupt)", "Tuzak (Trap)", "Hata (Error)", "Sinyal (Signal)"],
        a: "Kesme (Interrupt)",
        difficulty: "medium",
        week: 4,
        topic: "Kesme ve Tuzak",
        importance: "high",
        explanation: "Kesme (interrupt), donanım tarafından işlemciye gönderilen acil durum sinyalidir."
    },
    { 
        q: "Yazılım tarafından oluşturulan hata veya sistem çağrısı durumlarına ne denir?", 
        t: "mcq", 
        o: ["Tuzak (Trap)", "Kesme (Interrupt)", "Hata (Error)", "İstisna (Exception)"],
        a: "Tuzak (Trap)",
        difficulty: "medium",
        week: 4,
        topic: "Kesme ve Tuzak",
        importance: "high",
        explanation: "Tuzak (trap), yazılım kaynaklı istisnai durumlarda oluşur (örn: sıfıra bölme hatası)."
    },
    { 
        q: "İşletim sisteminin çekirdek kodunun güncellenmesi için sistem genellikle ne yapmalıdır?", 
        t: "mcq", 
        o: ["Sistem yeniden başlatılmalıdır", "Sadece uygulama yeniden başlatılır", "Otomatik güncellenir", "Hiçbir şey yapmaya gerek yoktur"], 
        a: "Sistem yeniden başlatılmalıdır",
        difficulty: "easy",
        week: 4,
        topic: "Çekirdek",
        importance: "low",
        explanation: "Çekirdek güncellemelerinden sonra değişikliklerin geçerli olması için sistem genellikle yeniden başlatılmalıdır."
    },
    
    // HAFTA 5: İşlem Yönetimi / Zamanlama Algoritmaları
    { 
        q: "Bir programın çalışmakta olan hâline ne denir?", 
        t: "mcq", 
        o: ["İşlem (Process)", "Thread", "Program", "Task"],
        a: "İşlem (Process)",
        difficulty: "easy",
        week: 5,
        topic: "İşlem Yönetimi",
        importance: "high",
        explanation: "İşlem (Process), belleğe yüklenmiş ve çalışmakta olan programdır."
    },
    { 
        q: "Bellekte çalışan en küçük iş birimi nedir?", 
        t: "mcq", 
        o: ["İşlem (Process)", "Byte", "Bit", "Instruction"],
        a: "İşlem (Process)",
        difficulty: "easy",
        week: 5,
        topic: "İşlem Yönetimi",
        importance: "high",
        explanation: "İşlem, bellekte çalışan en küçük bağımsız iş birimidir."
    },
    { 
        q: "Sabit diskte duran ve pasif kod olarak tanımlanan bileşen nedir?", 
        t: "mcq", 
        o: ["Program", "İşlem", "Thread", "Veri"],
        a: "Program",
        difficulty: "easy",
        week: 5,
        topic: "İşlem Yönetimi",
        importance: "medium",
        explanation: "Program, diskte saklanan pasif koddur; çalıştırıldığında işlem haline gelir."
    },
    { 
        q: "Çalışan ve aktif durumdaki kod olarak tanımlanan bileşen nedir?", 
        t: "mcq", 
        o: ["İşlem", "Program", "Dosya", "Klasör"],
        a: "İşlem",
        difficulty: "easy",
        week: 5,
        topic: "İşlem Yönetimi",
        importance: "medium",
        explanation: "İşlem, bellekte aktif olarak çalışan koddur."
    },
    { 
        q: "Program ve İşlem arasındaki temel farklardan biri nedir?", 
        t: "mcq", 
        o: ["Program bellekte yer kaplar, İşlem kaplamaz", "Program bellekte yer kaplamaz, İşlem bellekte alan tahsis eder", "Her ikisi de aynı miktarda bellek kullanır", "Her ikisi de bellekte yer kaplamaz"],
        a: "Program bellekte yer kaplamaz, İşlem bellekte alan tahsis eder",
        difficulty: "medium",
        week: 5,
        topic: "İşlem Yönetimi",
        importance: "medium",
        explanation: "İşlem çalıştığında bellekte kendine alan tahsis eder, program ise diskte pasif olarak durur."
    },
    { 
        q: "İşlem Durumları (Process States) arasında 'Ready' durumunun anlamı nedir?", 
        t: "mcq", 
        o: ["İşlem çalışmaya hazırdır", "İşlem çalışıyor", "İşlem bekleme durumunda", "İşlem sonlandı"],
        a: "İşlem çalışmaya hazırdır",
        difficulty: "medium",
        week: 5,
        topic: "İşlem Yönetimi",
        importance: "high",
        explanation: "Ready durumundaki işlem CPU'yu beklemektedir; zamanlayıcı tarafından seçilirse Running durumuna geçer."
    },
    { 
        q: "Bir işlemin CPU'da aktif olarak çalıştığı duruma ne denir?", 
        t: "mcq", 
        o: ["Running", "Ready", "Waiting", "Blocked"],
        a: "Running",
        difficulty: "easy",
        week: 5,
        topic: "İşlem Yönetimi",
        importance: "high",
        explanation: "Running durumunda işlem CPU'da komutlarını çalıştırmaktadır."
    },
    { 
        q: "Bir işlemin G/Ç (I/O) isteği, bir olay ya da sinyal beklediği duruma ne ad verilir?", 
        t: "mcq", 
        o: ["Waiting", "Running", "Ready", "New"],
        a: "Waiting",
        difficulty: "medium",
        week: 5,
        topic: "İşlem Yönetimi",
        importance: "high",
        explanation: "Waiting (veya Blocked) durumunda işlem, G/Ç veya bir olayın gerçekleşmesini bekler."
    },
    { 
        q: "Bir işlem çalışmasını tamamladığında hangi duruma geçer?", 
        t: "mcq", 
        o: ["Terminated", "Stopped", "Finished", "Closed"],
        a: "Terminated",
        difficulty: "easy",
        week: 5,
        topic: "İşlem Yönetimi",
        importance: "medium",
        explanation: "Terminated durumunda işlem çalışmasını tamamlamış ve sonlandırılmıştır."
    },
    { 
        q: "Bir işlemin tüm bilgilerini tutan veri yapısının kısaltması nedir?", 
        t: "mcq", 
        o: ["PCB", "PID", "CPU", "RAM"],
        a: "PCB",
        difficulty: "medium",
        week: 5,
        topic: "İşlem Yönetimi",
        importance: "high",
        explanation: "PCB (Process Control Block), işlemin durum bilgileri, CPU register değerleri, bellek bilgileri gibi tüm bilgileri içerir."
    },
    { 
        q: "PCB'nin açılımı nedir?", 
        t: "mcq", 
        o: ["Process Control Block", "Program Control Block", "Processor Control Base", "Process Code Block"],
        a: "Process Control Block",
        difficulty: "medium",
        week: 5,
        topic: "İşlem Yönetimi",
        importance: "high",
        explanation: "PCB, Process Control Block (İşlem Kontrol Bloğu) anlamına gelir."
    },
    { 
        q: "Aşağıdakilerden hangisi PCB içinde tutulan bilgilerden biri değildir?", 
        t: "mcq", 
        o: ["İşlem kimliği (PID)", "Program sayacı", "CPU register bilgileri", "Kullanıcının adı ve soyadı"], 
        a: "Kullanıcının adı ve soyadı",
        difficulty: "medium",
        week: 5,
        topic: "İşlem Yönetimi",
        importance: "medium",
        explanation: "PCB'de işlem durumu, PID, program sayacı, registerlar, bellek bilgileri vb. tutulur; kullanıcı kişisel bilgileri tutulmaz."
    },
    { 
        q: "Her işleme verilen benzersiz sayısal tanımlayıcıya ne denir?", 
        t: "mcq", 
        o: ["PID", "UID", "GID", "TID"],
        a: "PID",
        difficulty: "easy",
        week: 5,
        topic: "İşlem Yönetimi",
        importance: "high",
        explanation: "PID (Process ID), her işlemi benzersiz şekilde tanımlayan sayısal kimliktir."
    },
    { 
        q: "PID'nin açılımı nedir?", 
        t: "mcq", 
        o: ["Process ID", "Program ID", "Processor ID", "Primary ID"],
        a: "Process ID",
        difficulty: "medium",
        week: 5,
        topic: "İşlem Yönetimi",
        importance: "medium",
        explanation: "PID, Process ID (İşlem Kimliği) anlamına gelir."
    },
    { 
        q: "En basit zamanlama algoritması olup, ilk gelenin önce çalıştığı algoritmanın kısaltması nedir?", 
        t: "mcq", 
        o: ["FCFS", "SJF", "RR", "Priority"],
        a: "FCFS",
        difficulty: "medium",
        week: 5,
        topic: "Zamanlama Algoritmaları",
        importance: "high",
        explanation: "FCFS (First Come First Serve), işlemleri geliş sırasına göre çalıştıran en basit algoritmadır."
    },
    { 
        q: "FCFS zamanlama algoritmasının açılımı nedir?", 
        t: "mcq", 
        o: ["First Come First Serve", "Fast CPU First System", "First Call First Service", "First Control First Start"],
        a: "First Come First Serve",
        difficulty: "hard",
        week: 5,
        topic: "Zamanlama Algoritmaları",
        importance: "high",
        explanation: "FCFS, First Come First Serve (İlk Gelen İlk Servis Edilir) anlamına gelir."
    },
    { 
        q: "SJF zamanlama algoritmasının açılımı nedir?", 
        t: "mcq", 
        o: ["Shortest Job First", "Simple Job First", "System Job First", "Sequential Job First"],
        a: "Shortest Job First",
        difficulty: "hard",
        week: 5,
        topic: "Zamanlama Algoritmaları",
        importance: "high",
        explanation: "SJF, Shortest Job First (En Kısa İş Önce) anlamına gelir."
    },
    { 
        q: "Zamanlama algoritmaları arasında yer alan, her işleme eşit zaman dilimi veren algoritma hangisidir?", 
        t: "mcq", 
        o: ["Round Robin", "FCFS", "SJF", "Priority"],
        a: "Round Robin",
        difficulty: "hard",
        week: 5,
        topic: "Zamanlama Algoritmaları",
        importance: "medium",
        explanation: "Round Robin, her işleme sabit zaman dilimi (time quantum) vererek sırayla çalıştırır."
    },
    { 
        q: "Round Robin algoritmasında her işleme verilen sabit zaman dilimine ne denir?", 
        t: "mcq", 
        o: ["Time quantum", "Time slice", "CPU burst", "Clock cycle"],
        a: "Time quantum",
        difficulty: "hard",
        week: 5,
        topic: "Zamanlama Algoritmaları",
        importance: "medium",
        explanation: "Time quantum (zaman dilimi), Round Robin'de her işlemin CPU'yu kullanabileceği süreyi belirler."
    },
    { 
        q: "Bir işlemin çalışması tamamlanmadan CPU'dan alınması durumuna ne denir?", 
        t: "mcq", 
        o: ["Preemption", "Context Switch", "Interrupt", "Termination"],
        a: "Preemption",
        difficulty: "hard",
        week: 5,
        topic: "Zamanlama Algoritmaları",
        importance: "high",
        explanation: "Preemption (önalım), bir işlemin çalışmasının zorla durdurulması ve başka işleme geçilmesidir."
    },
    { 
        q: "FCFS algoritması preemptive midir?", 
        t: "mcq", 
        o: ["Hayır", "Evet", "Bazen", "Sisteme bağlı"], 
        a: "Hayır",
        difficulty: "medium",
        week: 5,
        topic: "Zamanlama Algoritmaları",
        importance: "high",
        explanation: "FCFS non-preemptive'dir; işlem bitene kadar CPU'yu bırakmaz."
    },
    { 
        q: "Round Robin algoritması preemptive midir?", 
        t: "mcq", 
        o: ["Evet", "Hayır", "Bazen", "Sisteme bağlı"], 
        a: "Evet",
        difficulty: "medium",
        week: 5,
        topic: "Zamanlama Algoritmaları",
        importance: "high",
        explanation: "Round Robin preemptive'dir; time quantum bittiğinde işlem CPU'dan alınır."
    },
    { 
        q: "SJF algoritmasının dezavantajı nedir?", 
        t: "mcq", 
        o: ["Uzun işlemler açlık (starvation) yaşayabilir", "Çok yavaş çalışır", "Sadece tek CPU'da çalışır", "Bellek kullanımı fazladır"], 
        a: "Uzun işlemler açlık (starvation) yaşayabilir",
        difficulty: "hard",
        week: 5,
        topic: "Zamanlama Algoritmaları",
        importance: "high",
        explanation: "SJF'de kısa işlemler öncelikli olduğundan, uzun işlemler sürekli ertelenebilir (starvation)."
    },
    { 
        q: "Bir işlemden diğerine geçiş sırasında CPU'nun durum bilgilerini kaydetme ve yükleme işlemine ne denir?", 
        t: "mcq", 
        o: ["Context Switch", "Process Switch", "Mode Switch", "Task Switch"],
        a: "Context Switch",
        difficulty: "hard",
        week: 5,
        topic: "İşlem Yönetimi",
        importance: "high",
        explanation: "Context Switch, CPU'nun bir işlemden diğerine geçerken durum bilgilerini kaydetme ve yükleme işlemidir."
    },
    { 
        q: "Context Switch sırasında CPU üretken iş yapmaz, bu duruma ne denir?", 
        t: "mcq", 
        o: ["Overhead", "Underflow", "Bottleneck", "Deadlock"],
        a: "Overhead",
        difficulty: "hard",
        week: 5,
        topic: "İşlem Yönetimi",
        importance: "medium",
        explanation: "Context Switch overhead'i, sistem performansını düşürür çünkü bu sürede yararlı iş yapılmaz."
    },
    { 
        q: "UNIX/Linux sistemlerinde yeni işlem oluşturmak için kullanılan sistem çağrısı nedir?", 
        t: "mcq", 
        o: ["fork", "exec", "create", "spawn"],
        a: "fork",
        difficulty: "hard",
        week: 5,
        topic: "İşlem Yönetimi",
        importance: "high",
        explanation: "fork() sistem çağrısı, mevcut işlemin bir kopyasını oluşturarak yeni işlem yaratır."
    },
    { 
        q: "Bir işlemi sonlandırmak için kullanılan sistem çağrısı nedir?", 
        t: "mcq", 
        o: ["exit", "kill", "stop", "terminate"],
        a: "exit",
        difficulty: "medium",
        week: 5,
        topic: "İşlem Yönetimi",
        importance: "medium",
        explanation: "exit() sistem çağrısı, işlemi sonlandırır ve kaynaklarını serbest bırakır."
    },
    { 
        q: "İşlemler arası iletişime ne denir?", 
        t: "mcq", 
        o: ["IPC", "RPC", "API", "DLL"],
        a: "IPC",
        difficulty: "medium",
        week: 5,
        topic: "İşlem İletişimi",
        importance: "high",
        explanation: "IPC (Inter-Process Communication), işlemlerin birbiriyle veri alışverişi yapmasını sağlar."
    },
    { 
        q: "IPC'nin açılımı nedir?", 
        t: "mcq", 
        o: ["Inter-Process Communication", "Internal Process Control", "Integrated Process Command", "Internet Protocol Connection"],
        a: "Inter-Process Communication",
        difficulty: "hard",
        week: 5,
        topic: "İşlem İletişimi",
        importance: "medium",
        explanation: "IPC, Inter-Process Communication (İşlemler Arası İletişim) anlamına gelir."
    },
    { 
        q: "Aşağıdakilerden hangisi bir IPC mekanizması değildir?", 
        t: "mcq", 
        o: ["Paylaşılan Bellek", "Mesaj Kuyrukları", "Pipe", "Cache Bellek"], 
        a: "Cache Bellek",
        difficulty: "medium",
        week: 5,
        topic: "İşlem İletişimi",
        importance: "medium",
        explanation: "IPC mekanizmaları: Paylaşılan bellek, mesaj kuyrukları, pipe, socket vb. Cache bellek IPC mekanizması değildir."
    },
    { 
        q: "Bir işlem içinde çalışan ve CPU tarafından zamanlanan en küçük birime ne denir?", 
        t: "mcq", 
        o: ["Thread", "Process", "Task", "Job"],
        a: "Thread",
        difficulty: "medium",
        week: 5,
        topic: "Thread",
        importance: "high",
        explanation: "Thread (iş parçacığı), bir işlem içinde paralel çalışabilen hafif yürütme birimidir."
    },
    { 
        q: "Thread'lerin aynı işlem içindeki diğer thread'lerle paylaştığı kaynak nedir?", 
        t: "mcq", 
        o: ["Kod ve Veri Segmenti", "Stack", "Registerlar", "Program Counter"], 
        a: "Kod ve Veri Segmenti",
        difficulty: "hard",
        week: 5,
        topic: "Thread",
        importance: "high",
        explanation: "Aynı işlemdeki thread'ler kod, veri ve heap'i paylaşır; ancak her birinin kendi stack ve register'ları vardır."
    },
    { 
        q: "Çok çekirdekli sistemlerde thread'lerin gerçekten paralel çalışması durumuna ne denir?", 
        t: "mcq", 
        o: ["Paralellik", "Concurrency", "Multitasking", "Time-sharing"],
        a: "Paralellik",
        difficulty: "medium",
        week: 5,
        topic: "Thread",
        importance: "medium",
        explanation: "Çok çekirdekli sistemlerde thread'ler aynı anda farklı çekirdeklerde çalışabilir (gerçek paralellik)."
    },
    { 
        q: "Birden fazla işlem veya thread'in paylaşılan kaynağa eşzamanlı erişimde oluşan problemlere ne denir?", 
        t: "mcq", 
        o: ["Race Condition", "Deadlock", "Starvation", "Thrashing"],
        a: "Race Condition",
        difficulty: "hard",
        week: 5,
        topic: "Senkronizasyon",
        importance: "high",
        explanation: "Race condition, paylaşılan kaynağa eşzamanlı erişimde tutarsızlıklara yol açan durumdur."
    },
    { 
        q: "Paylaşılan kaynağa aynı anda sadece bir işlemin erişebilmesini sağlayan kod bölgesine ne denir?", 
        t: "mcq", 
        o: ["Critical Section", "Protected Area", "Safe Zone", "Exclusive Region"],
        a: "Critical Section",
        difficulty: "hard",
        week: 5,
        topic: "Senkronizasyon",
        importance: "high",
        explanation: "Critical section (kritik bölge), paylaşılan kaynağa erişen kod bölümüdür ve korunması gerekir."
    },
    { 
        q: "Kritik bölgeyi korumak için kullanılan ve sadece bir işlemin kaynağa erişmesini sağlayan mekanizmaya ne denir?", 
        t: "mcq", 
        o: ["Mutex", "Semaphore", "Monitor", "Lock"],
        a: "Mutex",
        difficulty: "hard",
        week: 5,
        topic: "Senkronizasyon",
        importance: "high",
        explanation: "Mutex (Mutual Exclusion), kritik bölgeye tek bir işlemin girmesini sağlayan kilitleme mekanizmasıdır."
    },
    { 
        q: "Senkronizasyon için kullanılan ve sayaç mantığıyla çalışan yapıya ne denir?", 
        t: "mcq", 
        o: ["Semaphore", "Mutex", "Barrier", "Spinlock"],
        a: "Semaphore",
        difficulty: "hard",
        week: 5,
        topic: "Senkronizasyon",
        importance: "high",
        explanation: "Semaphore, sayaç kullanarak birden fazla işlemin senkronize edilmesini sağlar."
    },
    { 
        q: "İki veya daha fazla işlemin birbirini beklemesi ve hiçbirinin ilerleyememesi durumuna ne denir?", 
        t: "mcq", 
        o: ["Deadlock", "Livelock", "Starvation", "Race Condition"],
        a: "Deadlock",
        difficulty: "medium",
        week: 5,
        topic: "Deadlock",
        importance: "high",
        explanation: "Deadlock (kilitlenme), işlemlerin birbirlerinin kaynaklarını bekleyerek sonsuz döngüye girmesidir."
    },
    { 
        q: "Öncelik tabanlı zamanlamada, düşük öncelikli işlemlerin sürekli ertelenmesi durumuna ne denir?", 
        t: "mcq", 
        o: ["Starvation", "Deadlock", "Livelock", "Thrashing"],
        a: "Starvation",
        difficulty: "hard",
        week: 5,
        topic: "Zamanlama Algoritmaları",
        importance: "medium",
        explanation: "Starvation (açlık), düşük öncelikli işlemlerin sürekli ertelenerek hiç CPU alamama durumudur."
    },
    { 
        q: "Starvation problemini çözmek için zamanla işlem önceliğini artırma tekniğine ne denir?", 
        t: "mcq", 
        o: ["Aging", "Boosting", "Elevation", "Promotion"],
        a: "Aging",
        difficulty: "hard",
        week: 5,
        topic: "Zamanlama Algoritmaları",
        importance: "medium",
        explanation: "Aging, bekleyen işlemlerin önceliğini zamanla artırarak starvation'ı önler."
    },
    { 
        q: "Bir işlemin sistemde toplam geçirdiği süreye (bekleme + çalışma) ne denir?", 
        t: "mcq", 
        o: ["Turnaround Time", "Waiting Time", "Response Time", "Execution Time"],
        a: "Turnaround Time",
        difficulty: "hard",
        week: 5,
        topic: "Performans",
        importance: "medium",
        explanation: "Turnaround time, işlemin gelişinden tamamlanmasına kadar geçen toplam süredir."
    },
    { 
        q: "Bir işlemin hazır kuyruğunda beklediği süreye ne denir?", 
        t: "mcq", 
        o: ["Waiting Time", "Response Time", "Turnaround Time", "Burst Time"],
        a: "Waiting Time",
        difficulty: "medium",
        week: 5,
        topic: "Performans",
        importance: "medium",
        explanation: "Waiting time, işlemin ready kuyruğunda CPU'yu beklediği toplam süredir."
    },
    { 
        q: "Bir işlemin ilk kez CPU'ya atanana kadar geçen süreye ne denir?", 
        t: "mcq", 
        o: ["Response Time", "Waiting Time", "Turnaround Time", "Latency"],
        a: "Response Time",
        difficulty: "hard",
        week: 5,
        topic: "Performans",
        importance: "medium",
        explanation: "Response time, işlemin sisteme girmesinden ilk kez CPU almasına kadar geçen süredir."
    },
    { 
        q: "CPU'nun yararlı iş yaptığı sürenin toplam süreye oranına ne denir?", 
        t: "mcq", 
        o: ["CPU Utilization", "Throughput", "Efficiency", "Performance"],
        a: "CPU Utilization",
        difficulty: "medium",
        week: 5,
        topic: "Performans",
        importance: "high",
        explanation: "CPU Utilization (CPU kullanım oranı), CPU'nun ne kadar verimli kullanıldığını gösterir."
    },
    { 
        q: "Birim zamanda tamamlanan işlem sayısına ne denir?", 
        t: "mcq", 
        o: ["Throughput", "CPU Utilization", "Response Time", "Bandwidth"],
        a: "Throughput",
        difficulty: "medium",
        week: 5,
        topic: "Performans",
        importance: "medium",
        explanation: "Throughput (verim), sistemin birim zamanda kaç işlem tamamladığını gösterir."
    },
    { 
        q: "Birden fazla CPU veya çekirdeğe sahip sistemlere ne denir?", 
        t: "mcq", 
        o: ["Multiprocessor", "Multitasking", "Multiprogramming", "Multiuser"],
        a: "Multiprocessor",
        difficulty: "medium",
        week: 5,
        topic: "Çok İşlemcili Sistemler",
        importance: "medium",
        explanation: "Multiprocessor (çok işlemcili) sistemlerde birden fazla CPU paralel çalışır."
    },
    { 
        q: "Çok çekirdekli sistemlerde her işlemcinin kendi yerel belleği olduğu ve ağ üzerinden iletişim kurduğu yapıya ne denir?", 
        t: "mcq", 
        o: ["Distributed System", "Shared Memory System", "Clustered System", "Grid System"],
        a: "Distributed System",
        difficulty: "hard",
        week: 5,
        topic: "Çok İşlemcili Sistemler",
        importance: "low",
        explanation: "Distributed sistemlerde işlemciler fiziksel olarak ayrı ve ağ üzerinden haberleşir."
    },
    { 
        q: "Belirli süre kısıtlamaları içinde görevleri tamamlaması gereken sistemlere ne denir?", 
        t: "mcq", 
        o: ["Real-Time System", "Batch System", "Time-Sharing System", "Interactive System"],
        a: "Real-Time System",
        difficulty: "medium",
        week: 5,
        topic: "Gerçek Zamanlı Sistemler",
        importance: "low",
        explanation: "Real-time sistemlerde görevler belirli zaman sınırları içinde tamamlanmalıdır (örn: uçak kontrol sistemleri)."
    },
    { 
        q: "Bir işletim sisteminin çoklu görev (multitasking) yapabilmesi için hangi özellik gereklidir?", 
        t: "mcq", 
        o: ["Zamanlama mekanizması", "Sadece çok çekirdekli CPU", "Grafik arayüz", "Ağ bağlantısı"], 
        a: "Zamanlama mekanizması",
        difficulty: "medium",
        week: 5,
        topic: "Zamanlama Algoritmaları",
        importance: "high",
        explanation: "Multitasking için zamanlayıcı gereklidir; tek çekirdekli CPU'da bile zaman paylaşımı ile yapılabilir."
    },
    { 
        q: "Bir işlemin bellek alanı hangi bölümlerden oluşur?", 
        t: "mcq", 
        o: ["Kod, veri, heap ve stack", "Sadece kod ve veri", "Sadece heap ve stack", "Sadece kod"], 
        a: "Kod, veri, heap ve stack",
        difficulty: "hard",
        week: 5,
        topic: "İşlem Yönetimi",
        importance: "high",
        explanation: "İşlem bellek alanı dört ana bölümden oluşur: kod (text), veri (data), heap (dinamik bellek) ve stack (yerel değişkenler)."
    },
    { 
        q: "UNIX/Linux sistemlerinde bir işlemin önceliğini değiştirmek için kullanılan komut nedir?", 
        t: "mcq", 
        o: ["nice", "priority", "setprio", "renice"],
        a: "nice",
        difficulty: "hard",
        week: 5,
        topic: "Zamanlama Algoritmaları",
        importance: "low",
        explanation: "nice komutu, işlem önceliğini ayarlamak için kullanılır."
    },
    { 
        q: "Bir işlemin CPU'da çalışırken kesintiye uğraması ve daha yüksek öncelikli işleme geçilmesi durumuna ne denir?", 
        t: "mcq", 
        o: ["Preemptive scheduling", "Non-preemptive scheduling", "Context switch", "Process migration"],
        a: "Preemptive scheduling",
        difficulty: "hard",
        week: 5,
        topic: "Zamanlama Algoritmaları",
        importance: "high",
        explanation: "Preemptive scheduling'de işlemci, çalışan işlemi durdurarak daha yüksek öncelikli işleme geçebilir."
    },
    { 
        q: "Çoklu işlemci sistemlerde işlemciler arasında yük dengelemesi yapan bileşene ne denir?", 
        t: "mcq", 
        o: ["Scheduler", "Dispatcher", "Allocator", "Balancer"],
        a: "Scheduler",
        difficulty: "hard",
        week: 5,
        topic: "Zamanlama Algoritmaları",
        importance: "medium",
        explanation: "Scheduler (zamanlayıcı), işlemleri işlemcilere dağıtarak yük dengelemesi yapar."
    },
    { 
        q: "Bir işlemin bellekteki başlangıç adresini tutan register nedir?", 
        t: "mcq", 
        o: ["Base register", "Limit register", "Program counter", "Stack pointer"],
        a: "Base register",
        difficulty: "hard",
        week: 5,
        topic: "İşlem Yönetimi",
        importance: "medium",
        explanation: "Base register, işlemin bellek alanının başlangıç adresini tutar."
    },
    { 
        q: "Bir işlemin çocuk işlem yaratması durumunda, çocuk işlemin kaynakları kimden alır?", 
        t: "mcq", 
        o: ["Ebeveyn işlemden", "İşletim sisteminden direkt", "Diğer işlemlerden", "Disk alanından"], 
        a: "Ebeveyn işlemden",
        difficulty: "medium",
        week: 5,
        topic: "İşlem Yönetimi",
        importance: "medium",
        explanation: "Çocuk işlem, ebeveyn işlemin kaynaklarını kullanır veya işletim sistemi yeni kaynaklar tahsis eder."
    },
    { 
        q: "Bir işlemin beklemeden dolayı CPU kullanmadığı duruma ne denir?", 
        t: "mcq", 
        o: ["Idle", "Blocked", "Suspended", "Stopped"],
        a: "Idle",
        difficulty: "easy",
        week: 5,
        topic: "İşlem Yönetimi",
        importance: "low",
        explanation: "Idle durumunda sistem veya işlem beklemede olup CPU kullanmaz."
    }
];

// Toplam soru sayısını konsola yazdır
console.log(`✅ Toplam ${window.questionBank.length} soru yüklendi!`);
