// İşletim Sistemleri Quiz - Soru Bankası (Tümü 4 Şıklı Test)
// Bu dosya HTML sayfası tarafından yüklenecek

window.questionBank = [
    // HAFTA 1: Windows, Mac OS, Linux/Pardus, Mobil, Genel Kavramlar
    { 
        q: "Bilgisayarda yapmak istediğimiz işleri donanıma tercüme eden bileşen nedir?", 
        t: "mcq", 
        o: ["İşletim Sistemi", "BIOS", "Donanım Sürücüsü", "Uygulama Yazılımı"],
        a: "İşletim Sistemi",
        difficulty: "easy",
        week: 1,
        topic: "Genel Kavramlar",
        importance: "high",
        explanation: "İşletim sistemi, kullanıcı ile donanım arasındaki köprüdür. Kullanıcının komutlarını donanımın anlayacağı şekilde çevirir."
    },
    { 
        q: "İşletim sistemi bilgisayarın neye benzetilebilir?", 
        t: "mcq", 
        o: ["Trafik Polisi", "Motor", "Yakıt", "Tekerlek"],
        a: "Trafik Polisi",
        difficulty: "easy",
        week: 1,
        topic: "Genel Kavramlar",
        importance: "high",
        explanation: "İşletim sistemi, tüm sistem kaynaklarını koordine eder ve trafiği yönetir, tıpkı bir trafik polisi gibi."
    },
    { 
        q: "İşletim sistemlerinin temel amaçlarından biri bilgisayarın kullanıcılar tarafından kolay kullanılmasını sağlamaktır.", 
        t: "mcq", 
        o: ["Doğru", "Yanlış", "Kısmen Doğru", "Belirsiz"], 
        a: "Doğru",
        difficulty: "easy",
        week: 1,
        topic: "Genel Kavramlar",
        importance: "medium",
        explanation: "İşletim sisteminin temel amaçlarından ilki, bilgisayarın kolay kullanılmasını sağlamaktır."
    },
    { 
        q: "İşletim sistemlerinin temel amaçlarından biri donanım kaynaklarının verimli bir şekilde kullanılmasını sağlamaktır.", 
        t: "mcq", 
        o: ["Doğru", "Yanlış", "Sadece Windows'ta", "Sadece Linux'ta"], 
        a: "Doğru",
        difficulty: "easy",
        week: 1,
        topic: "Genel Kavramlar",
        importance: "high",
        explanation: "İşletim sisteminin temel amaçlarından ikincisi, donanım kaynaklarının verimli kullanılmasını sağlamaktır."
    },
    { 
        q: "Bir bilgisayar sistemi genel olarak dört temel bileşenden oluşur. Bunlardan biri değildir?", 
        t: "mcq", 
        o: ["Kullanıcılar", "Uygulamalar/Programlar", "Donanım Aygıtları", "Ağ Yönlendiricileri"], 
        a: "Ağ Yönlendiricileri",
        difficulty: "medium",
        week: 1,
        topic: "Genel Kavramlar",
        importance: "high",
        explanation: "Dört temel bileşen: Kullanıcılar, Uygulamalar/Programlar, İşletim Sistemi ve Donanım Aygıtlarıdır."
    },
    { 
        q: "Kelime işlemci veya hesap makinası gibi yazılımlar, bir bilgisayar sisteminin hangi temel bileşenine örnektir?", 
        t: "mcq", 
        o: ["Uygulamalar/Programlar", "İşletim Sistemi", "Donanım", "Sürücüler"],
        a: "Uygulamalar/Programlar",
        difficulty: "easy",
        week: 1,
        topic: "Genel Kavramlar",
        importance: "medium",
        explanation: "Kelime işlemci ve hesap makinası gibi yazılımlar, Uygulamalar/Programlar bileşenine örnektir."
    },
    { 
        q: "İşletim sistemi olmadan bilgisayar sadece bir donanım yığınıdır.", 
        t: "mcq", 
        o: ["Doğru", "Yanlış", "Kısmen Doğru", "Sadece eski bilgisayarlarda doğru"], 
        a: "Doğru",
        difficulty: "easy",
        week: 1,
        topic: "Genel Kavramlar",
        importance: "medium",
        explanation: "İşletim sistemi olmadan bilgisayar, hiçbir işlev gösteremeyen bir donanım yığınından ibarettir."
    },
    { 
        q: "Microsoft firması tarafından geliştirilen işletim sistemi hangisidir?", 
        t: "mcq", 
        o: ["Windows", "Mac OS", "Linux", "Unix"],
        a: "Windows",
        difficulty: "easy",
        week: 1,
        topic: "Windows",
        importance: "low"
    },
    { 
        q: "Apple firması tarafından geliştirilen işletim sistemi hangisidir?", 
        t: "mcq", 
        o: ["Mac OS", "Windows", "Linux", "Android"],
        a: "Mac OS",
        difficulty: "easy",
        week: 1,
        topic: "Mac OS",
        importance: "low"
    },
    { 
        q: "Windows'ta işletim sistemini ilk çalıştırdığımızda karşımıza gelen ekrana ne denir?", 
        t: "mcq", 
        o: ["Masaüstü", "Başlat Menüsü", "Görev Çubuğu", "Kontrol Paneli"],
        a: "Masaüstü",
        difficulty: "easy",
        week: 1,
        topic: "Windows",
        importance: "high",
        explanation: "İşletim sistemini ilk çalıştırdığımızda karşımıza gelen ekrana 'Masaüstü' denir."
    },
    { 
        q: "Windows Masaüstünün temel bileşenleri nelerdir?", 
        t: "mcq", 
        o: ["Görev çubuğu, Başlat menüsü, Hızlı erişim menüleri", "Sadece Başlat menüsü", "Sadece simgeler", "Sadece duvar kağıdı"],
        a: "Görev çubuğu, Başlat menüsü, Hızlı erişim menüleri",
        difficulty: "medium",
        week: 1,
        topic: "Windows",
        importance: "medium",
        explanation: "Masaüstünün temel bileşenleri: görev çubuğu, başlat menüsü ve hızlı erişim menüleridir."
    },
    { 
        q: "Hangi işletim sisteminde Başlat Menüsü, o sisteme özel bir öge olarak belirtilmiştir?", 
        t: "mcq", 
        o: ["Windows", "Mac OS", "Linux", "Unix"],
        a: "Windows",
        difficulty: "medium",
        week: 1,
        topic: "Windows",
        importance: "high",
        explanation: "Başlat menüsü Microsoft Windows'a özel bir ögedir."
    },
    { 
        q: "Windows'ta bir dosyayı aynı sürücü altındaki başka bir klasöre 'sürükleyip bırakmak' ne anlama gelir?", 
        t: "mcq", 
        o: ["Dosya bulunduğu yerden silinip yeni konuma yerleştirilir", "Dosya kopyalanır, eski konumunda kalır", "İşlem hata verir", "Dosya kısayolu oluşturulur"], 
        a: "Dosya bulunduğu yerden silinip yeni konuma yerleştirilir",
        difficulty: "hard",
        week: 1,
        topic: "Windows",
        importance: "medium",
        explanation: "Aynı sürücü içinde sürükle-bırak işlemi yapıldığında dosya taşınır (eski konumdan silinir)."
    },
    { 
        q: "Windows'ta bir dosyayı farklı bir sürücüdeki bir klasöre 'sürükleyip bırakmak' ne anlama gelir?", 
        t: "mcq", 
        o: ["Dosya kopyalanır, eski konumunda kalır", "Dosya bulunduğu yerden silinip yeni konuma yerleştirilir", "İşlem hata verir", "Dosyanın sahipliği değiştirilir"], 
        a: "Dosya kopyalanır, eski konumunda kalır",
        difficulty: "hard",
        week: 1,
        topic: "Windows",
        importance: "medium",
        explanation: "Farklı sürücüler arasında sürükle-bırak işlemi yapıldığında dosya kopyalanır, orijinal dosya yerinde kalır."
    },
    { 
        q: "Windows işletim sisteminde dosya ve klasörleri yönetmek için kullanılan araç nedir?", 
        t: "mcq", 
        o: ["Dosya Gezgini", "Kontrol Paneli", "Görev Yöneticisi", "Sistem Ayarları"],
        a: "Dosya Gezgini",
        difficulty: "easy",
        week: 1,
        topic: "Windows",
        importance: "high",
        explanation: "Windows'ta Dosya Gezgini (File Explorer), dosya ve klasörlerin yönetimi için kullanılır."
    },
    { 
        q: "Mac OS masaüstünde, ekranın alt kısmında bulunan özelleştirilebilir uygulamalar alanına ne ad verilir?", 
        t: "mcq", 
        o: ["Dock", "Taskbar", "Panel", "Launcher"],
        a: "Dock",
        difficulty: "easy",
        week: 1,
        topic: "Mac OS",
        importance: "high",
        explanation: "Ekranın alt kısmında kullanıcı tarafından özelleştirilebilen uygulamalar alanına 'dock' denir."
    },
    { 
        q: "Mac OS işletim sisteminin dosya gezginine verilen isim nedir?", 
        t: "mcq", 
        o: ["Finder", "Explorer", "Navigator", "Browser"],
        a: "Finder",
        difficulty: "medium",
        week: 1,
        topic: "Mac OS",
        importance: "high",
        explanation: "Finder, Mac OS işletim sisteminin dosya gezginidir."
    },
    { 
        q: "Mac OS'ta hangi menü bir nevi başlat menüsü görevi görür?", 
        t: "mcq", 
        o: ["Git Menüsü", "Dosya Menüsü", "Düzen Menüsü", "Görünüm Menüsü"],
        a: "Git Menüsü",
        difficulty: "medium",
        week: 1,
        topic: "Mac OS",
        importance: "medium",
        explanation: "Git menüsü, Mac OS'ta bir nevi başlat menüsü görevi görür."
    },
    { 
        q: "Mac OS'ta bilgisayarı kapatmak için bulunan seçeneklerden biri değildir?", 
        t: "mcq", 
        o: ["Ağ Bağlantısını Kes", "Uyu", "Yeniden Başla", "Sistemi Kapat"], 
        a: "Ağ Bağlantısını Kes",
        difficulty: "medium",
        week: 1,
        topic: "Mac OS",
        importance: "medium",
        explanation: "Mac OS'ta kapatma seçenekleri: Uyu, Yeniden Başla, Sistemi Kapat, Kullanıcı Oturumunu Kapat."
    },
    { 
        q: "Linux en basit ifade ile nedir?", 
        t: "mcq", 
        o: ["Özgür bir işletim sistemi çekirdeğidir", "Bir uygulama programıdır", "Bir donanım bileşenidir", "Bir web tarayıcısıdır"],
        a: "Özgür bir işletim sistemi çekirdeğidir",
        difficulty: "medium",
        week: 1,
        topic: "Linux/Pardus",
        importance: "high",
        explanation: "Linux, en basit ifadeyle özgür bir işletim sistemi çekirdeğidir."
    },
    { 
        q: "Linux çekirdeği üzerine geliştirilen işletim sistemlerine ne ad verilir?", 
        t: "mcq", 
        o: ["Linux Dağıtımları", "Linux Eklentileri", "Linux Modülleri", "Linux Paketleri"],
        a: "Linux Dağıtımları",
        difficulty: "medium",
        week: 1,
        topic: "Linux/Pardus",
        importance: "medium",
        explanation: "Linux çekirdeği üzerine geliştirilen işletim sistemlerine 'Linux dağıtımları' adı verilir."
    },
    { 
        q: "Kaynak kodlarının herkes tarafından görülebiliyor, değiştirilebiliyor ve serbestçe dağıtılabiliyor olması, yazılımın hangi özelliğini ifade eder?", 
        t: "mcq", 
        o: ["Açık Kaynak Kodlu", "Kapalı Kaynak Kodlu", "Shareware", "Freeware"],
        a: "Açık Kaynak Kodlu",
        difficulty: "easy",
        week: 1,
        topic: "Linux/Pardus",
        importance: "high",
        explanation: "Kaynak kodlarının görülebilir, değiştirilebilir ve dağıtılabilir olması, 'açık kaynak kodlu' yazılımların özelliğidir."
    },
    { 
        q: "Pardus işletim sistemi ilk kez çalıştırıldığında ekrana gelen bir kerelik çalışan yapılandırma yardımcısının adı nedir?", 
        t: "mcq", 
        o: ["Kaptan", "Yardımcı", "Rehber", "Kurulum"],
        a: "Kaptan",
        difficulty: "medium",
        week: 1,
        topic: "Linux/Pardus",
        importance: "high",
        explanation: "Pardus'ta ilk çalıştırmada 'Kaptan' isimli yapılandırma yardımcısı çalışır."
    },
    { 
        q: "Pardus, hangi kurum bünyesinde geliştirilmeye başlanmıştır?", 
        t: "mcq", 
        o: ["TÜBİTAK", "ASELSAN", "ODTÜ", "Boğaziçi Üniversitesi"],
        a: "TÜBİTAK",
        difficulty: "medium",
        week: 1,
        topic: "Linux/Pardus",
        importance: "medium",
        explanation: "Pardus, TÜBİTAK bünyesinde geliştirilen yerli ve milli işletim sistemidir."
    },
    { 
        q: "Pardus'un ilk sürümü hangi yıl yayınlanmıştır?", 
        t: "mcq", 
        o: ["2005", "2000", "2010", "2015"],
        a: "2005",
        difficulty: "medium",
        week: 1,
        topic: "Linux/Pardus",
        importance: "low",
        explanation: "Pardus'un ilk sürümü 2005 yılında yayınlanmıştır."
    },
    { 
        q: "Windows ve Mac OS gibi işletim sistemleri, geliştirme merkezlerine göre hangi tip işletim sistemleridir?", 
        t: "mcq", 
        o: ["Sahipli", "Açık Kaynak", "Özgür", "Dağıtık"],
        a: "Sahipli",
        difficulty: "medium",
        week: 1,
        topic: "Linux/Pardus",
        importance: "medium",
        explanation: "Windows ve Mac OS gibi işletim sistemleri, firmalara bağlı sahipli işletim sistemleridir."
    },
    { 
        q: "Mobil işletim sistemleri, normal işletim sistemlerine göre nasıl bir yapıdadır?", 
        t: "mcq", 
        o: ["Daha basit", "Daha karmaşık", "Aynı seviyede", "Daha ağır"],
        a: "Daha basit",
        difficulty: "easy",
        week: 1,
        topic: "Mobil İS",
        importance: "medium",
        explanation: "Mobil işletim sistemleri, masaüstü işletim sistemlerine göre daha basit yapıdadır."
    },
    { 
        q: "Android işletim sistemi hangi çekirdek üzerine kurulmuştur?", 
        t: "mcq", 
        o: ["Linux", "Unix", "Windows NT", "BSD"],
        a: "Linux",
        difficulty: "medium",
        week: 1,
        topic: "Mobil İS",
        importance: "high",
        explanation: "Android, Linux çekirdeği üzerine kurulu bir mobil işletim sistemidir."
    },
    { 
        q: "Apple'ın mobil cihazları için geliştirdiği işletim sisteminin adı nedir?", 
        t: "mcq", 
        o: ["iOS", "Android", "Windows Mobile", "Symbian"],
        a: "iOS",
        difficulty: "easy",
        week: 1,
        topic: "Mobil İS",
        importance: "medium",
        explanation: "iOS, Apple tarafından iPhone ve iPad için geliştirilmiş mobil işletim sistemidir."
    },
    
    // HAFTA 3: Mantıksal Yapı / Fonksiyonlar / Tarihçe
    { 
        q: "İşletim sisteminin temel görevlerinden biri nedir?", 
        t: "mcq", 
        o: ["Donanımı soyutlamak", "Oyun oynamak", "İnternet bağlantısı kurmak", "Video izlemek"],
        a: "Donanımı soyutlamak",
        difficulty: "easy",
        week: 3,
        topic: "Fonksiyonlar",
        importance: "high",
        explanation: "İşletim sisteminin görevleri: Donanımı soyutlamak, kaynakları yönetmek, kolay ortam sağlamak."
    },
    { 
        q: "İşletim sisteminin hangi görevi, kullanıcıların donanım detayları ile ilgilenmesini gereksiz kılar?", 
        t: "mcq", 
        o: ["Donanımı soyutlamak", "Kaynak yönetimi", "Güvenlik sağlamak", "Ağ yönetimi"],
        a: "Donanımı soyutlamak",
        difficulty: "medium",
        week: 3,
        topic: "Fonksiyonlar",
        importance: "high",
        explanation: "Donanım soyutlama sayesinde kullanıcılar donanım detayları ile uğraşmak zorunda kalmaz."
    },
    { 
        q: "CPU, RAM, disk gibi kaynakların adil dağıtımını yapan işletim sistemi görevine ne denir?", 
        t: "mcq", 
        o: ["Kaynak Yönetimi", "Dosya Yönetimi", "Ağ Yönetimi", "Güvenlik Yönetimi"],
        a: "Kaynak Yönetimi",
        difficulty: "easy",
        week: 3,
        topic: "Fonksiyonlar",
        importance: "high",
        explanation: "Kaynak yönetimi, CPU, RAM, disk gibi kaynakların işlemler arasında adil dağıtımını sağlar."
    },
    { 
        q: "1950'lerde kullanılan ve kart delme makineleri ile veri girişinin yapıldığı sistemlere ne ad verilir?", 
        t: "mcq", 
        o: ["Batch Sistemler", "Real-time Sistemler", "Distributed Sistemler", "Cloud Sistemler"],
        a: "Batch Sistemler",
        difficulty: "medium",
        week: 3,
        topic: "İS Tarihi",
        importance: "high",
        explanation: "1950'lerde kart delme makineleri ile batch (toplu işlem) sistemler kullanılırdı."
    },
    { 
        q: "Çoklu programlama ve zaman paylaşımlı sistemlerin doğuşu hangi yılları kapsamaktadır?", 
        t: "mcq", 
        o: ["1960'lar", "1950'ler", "1970'ler", "1980'ler"],
        a: "1960'lar",
        difficulty: "medium",
        week: 3,
        topic: "İS Tarihi",
        importance: "medium",
        explanation: "1960'larda çoklu programlama ve zaman paylaşımlı sistemler geliştirildi."
    },
    { 
        q: "UNIX'in doğuşu hangi yılları kapsamaktadır?", 
        t: "mcq", 
        o: ["1970'ler", "1960'lar", "1980'ler", "1990'lar"],
        a: "1970'ler",
        difficulty: "easy",
        week: 3,
        topic: "İS Tarihi",
        importance: "medium",
        explanation: "UNIX işletim sistemi 1970'lerde geliştirildi."
    },
    { 
        q: "MS-DOS ve kişisel bilgisayarların yaygınlaşması hangi yıllara denk gelmektedir?", 
        t: "mcq", 
        o: ["1980'ler", "1970'ler", "1990'lar", "2000'ler"],
        a: "1980'ler",
        difficulty: "easy",
        week: 3,
        topic: "İS Tarihi",
        importance: "medium",
        explanation: "1980'lerde MS-DOS ve kişisel bilgisayarlar yaygınlaştı."
    },
    { 
        q: "Windows ve grafik arayüzlerin gelişimi hangi yıllarda gerçekleşmiştir?", 
        t: "mcq", 
        o: ["1990'lar", "1980'ler", "2000'ler", "1970'ler"],
        a: "1990'lar",
        difficulty: "easy",
        week: 3,
        topic: "İS Tarihi",
        importance: "low",
        explanation: "1990'larda Windows ve grafik arayüzler gelişim gösterdi."
    },
    { 
        q: "RAM yetersiz kaldığında disk alanının kullanılması hangi bellek yönetim tekniği ile ilgilidir?", 
        t: "mcq", 
        o: ["Sanal Bellek", "Cache Bellek", "ROM", "BIOS"],
        a: "Sanal Bellek",
        difficulty: "easy",
        week: 3,
        topic: "Bellek Yönetimi",
        importance: "high",
        explanation: "Sanal bellek, RAM yetersiz kaldığında disk alanını kullanarak bellek genişletir."
    },
    { 
        q: "Sanal bellekte kullanılan iki temel yöntem Sayfalama (Paging) ve nedir?", 
        t: "mcq", 
        o: ["Segmentasyon", "Swapping", "Caching", "Buffering"],
        a: "Segmentasyon",
        difficulty: "medium",
        week: 3,
        topic: "Bellek Yönetimi",
        importance: "high",
        explanation: "Sanal bellek iki temel yöntem kullanır: Sayfalama (Paging) ve Segmentasyon."
    },
    { 
        q: "Mantıksal adresi fiziksel adrese dönüştüren birime ne denir?", 
        t: "mcq", 
        o: ["MMU", "CPU", "ALU", "CU"],
        a: "MMU",
        difficulty: "hard",
        week: 3,
        topic: "Bellek Yönetimi",
        importance: "high",
        explanation: "MMU (Memory Management Unit), sanal bellek sisteminde mantıksal adresleri fiziksel adreslere çevirir."
    },
    { 
        q: "MMU'nun açılımı nedir?", 
        t: "mcq", 
        o: ["Memory Management Unit", "Memory Module Unit", "Main Memory Unit", "Multi Memory Unit"],
        a: "Memory Management Unit",
        difficulty: "hard",
        week: 3,
        topic: "Bellek Yönetimi",
        importance: "medium",
        explanation: "MMU, Memory Management Unit (Bellek Yönetim Birimi) anlamına gelir."
    },
    { 
        q: "Dosya yönetiminde, kalıcı veri saklama birimine ne ad verilir?", 
        t: "mcq", 
        o: ["Dosya", "RAM", "Cache", "Register"],
        a: "Dosya",
        difficulty: "easy",
        week: 3,
        topic: "Dosya Yönetimi",
        importance: "medium",
        explanation: "Dosya, kalıcı veri saklama birimidir."
    },
    { 
        q: "FAT32, NTFS, ext4 neye örnektir?", 
        t: "mcq", 
        o: ["Dosya Sistemleri", "İşletim Sistemleri", "Donanım Bileşenleri", "Programlama Dilleri"],
        a: "Dosya Sistemleri",
        difficulty: "medium",
        week: 3,
        topic: "Dosya Yönetimi",
        importance: "high",
        explanation: "FAT32, NTFS, ext4 farklı dosya sistemlerine örnektir."
    },
    { 
        q: "FAT32'nin özelliklerinden biri değildir?", 
        t: "mcq", 
        o: ["Gelişmiş güvenlik özellikleri sunar", "Basit bir dosya sistemidir", "Uyumlu bir dosya sistemidir", "Sınırlı özelliklere sahiptir"], 
        a: "Gelişmiş güvenlik özellikleri sunar",
        difficulty: "medium",
        week: 3,
        topic: "Dosya Yönetimi",
        importance: "high",
        explanation: "FAT32 basit ve uyumludur ancak güvenlik özellikleri sınırlıdır. NTFS gelişmiş güvenlik sunar."
    },
    { 
        q: "Linux işletim sistemleri için yaygın olarak kullanılan dosya sistemi nedir?", 
        t: "mcq", 
        o: ["ext4", "NTFS", "FAT32", "HFS+"],
        a: "ext4",
        difficulty: "medium",
        week: 3,
        topic: "Dosya Yönetimi",
        importance: "high",
        explanation: "ext4, Linux sistemlerde yaygın olarak kullanılan dosya sistemidir."
    },
    { 
        q: "Windows'un modern dosya sistemi hangisidir?", 
        t: "mcq", 
        o: ["NTFS", "FAT32", "ext4", "HFS+"],
        a: "NTFS",
        difficulty: "easy",
        week: 3,
        topic: "Dosya Yönetimi",
        importance: "high",
        explanation: "NTFS (New Technology File System), Windows'un modern ve gelişmiş dosya sistemidir."
    },
    { 
        q: "RAID 0'ın avantajı nedir?", 
        t: "mcq", 
        o: ["Hız", "Güvenlik", "Yedekleme", "Düşük maliyet"],
        a: "Hız",
        difficulty: "medium",
        week: 3,
        topic: "Disk Yönetimi",
        importance: "medium",
        explanation: "RAID 0, striping yaparak veri okuma/yazma hızını artırır ancak yedekleme yapmaz."
    },
    { 
        q: "Aynalama (mirroring) yapan RAID teknolojisi hangisidir?", 
        t: "mcq", 
        o: ["RAID 1", "RAID 0", "RAID 5", "RAID 10"],
        a: "RAID 1",
        difficulty: "medium",
        week: 3,
        topic: "Disk Yönetimi",
        importance: "high",
        explanation: "RAID 1, verileri iki diske aynalayarak (mirroring) yedekleme sağlar."
    },
    { 
        q: "RAID teknolojisinin temel amacı nedir?", 
        t: "mcq", 
        o: ["Hem hız hem veri güvenliği sağlamak", "Sadece hız artırmak", "Sadece veri güvenliği sağlamak", "Disk alanından tasarruf etmek"], 
        a: "Hem hız hem veri güvenliği sağlamak",
        difficulty: "medium",
        week: 3,
        topic: "Disk Yönetimi",
        importance: "medium",
        explanation: "RAID teknolojisi, farklı seviyelerde hem performans hem de veri güvenliği sağlamayı amaçlar."
    },
    { 
        q: "Klavye, fare, yazıcı gibi donanımların yönetiminden hangi işletim sistemi bileşeni sorumludur?", 
        t: "mcq", 
        o: ["Giriş/Çıkış Yönetimi", "Bellek Yönetimi", "İşlem Yönetimi", "Dosya Yönetimi"],
        a: "Giriş/Çıkış Yönetimi",
        difficulty: "easy",
        week: 3,
        topic: "G/Ç Yönetimi",
        importance: "medium",
        explanation: "Giriş/Çıkış (I/O) yönetimi, tüm donanım aygıtlarının işletim sistemi tarafından kontrol edilmesini sağlar."
    },
    { 
        q: "Donanım ile işletim sistemi arasındaki arayüzü sağlayan yazılımlara ne denir?", 
        t: "mcq", 
        o: ["Sürücüler (Drivers)", "Firmware", "BIOS", "Uygulamalar"],
        a: "Sürücüler (Drivers)",
        difficulty: "easy",
        week: 3,
        topic: "G/Ç Yönetimi",
        importance: "high",
        explanation: "Sürücüler (drivers), donanım ile işletim sistemi arasında iletişim sağlar."
    },
    { 
        q: "İşletim sisteminin, kullanıcıların ve işlemlerin kaynaklara erişimini kontrol etme görevine ne denir?", 
        t: "mcq", 
        o: ["Güvenlik ve Koruma", "Kaynak Yönetimi", "İşlem Yönetimi", "Bellek Yönetimi"],
        a: "Güvenlik ve Koruma",
        difficulty: "medium",
        week: 3,
        topic: "Güvenlik",
        importance: "high",
        explanation: "İşletim sistemi, güvenlik ve koruma mekanizmaları ile kaynaklara erişimi kontrol eder."
    },
    { 
        q: "Bir kullanıcının sisteme giriş yaparken kimliğinin doğrulanması işlemine ne denir?", 
        t: "mcq", 
        o: ["Kimlik Doğrulama (Authentication)", "Yetkilendirme (Authorization)", "Şifreleme (Encryption)", "Denetim (Auditing)"],
        a: "Kimlik Doğrulama (Authentication)",
        difficulty: "easy",
        week: 3,
        topic: "Güvenlik",
        importance: "high",
        explanation: "Kimlik doğrulama (authentication), kullanıcının kim olduğunu doğrulama işlemidir."
    },
    { 
        q: "İşletim sisteminin kaynak yönetimi görevlerinden biri değildir?", 
        t: "mcq", 
        o: ["Kullanıcı arayüzü tasarlamak", "CPU zamanını dağıtmak", "Bellek tahsis etmek", "Dosya sistemini yönetmek"], 
        a: "Kullanıcı arayüzü tasarlamak",
        difficulty: "medium",
        week: 3,
        topic: "Fonksiyonlar",
        importance: "medium",
        explanation: "Kaynak yönetimi CPU, bellek, disk gibi donanım kaynaklarının yönetimini içerir; arayüz tasarımı kullanıcı deneyimi ile ilgilidir."
    },
    { 
        q: "İşletim sisteminin donanım ve yazılım arasındaki konumunu belirten kavram nedir?", 
        t: "mcq", 
        o: ["Ara Katman", "Üst Katman", "Alt Katman", "Yan Katman"],
        a: "Ara Katman",
        difficulty: "medium",
        week: 3,
        topic: "Fonksiyonlar",
        importance: "high",
        explanation: "İşletim sistemi, kullanıcı/uygulama ile donanım arasında ara katman (middleware) görevi görür."
    },
    { 
        q: "Bir dosya sisteminde dizin yapısının en üst noktasına ne denir?", 
        t: "mcq", 
        o: ["Root", "Home", "User", "System"],
        a: "Root",
        difficulty: "easy",
        week: 3,
        topic: "Dosya Yönetimi",
        importance: "medium",
        explanation: "Root dizini, dosya sisteminin en üst seviyesidir (Linux'ta /, Windows'ta C:\\)."
    },
    { 
        q: "Sanal bellek kullanıldığında diskte kullanılan alana ne ad verilir?", 
        t: "mcq", 
        o: ["Swap", "Cache", "Buffer", "Partition"],
        a: "Swap",
        difficulty: "medium",
        week: 3,
        topic: "Bellek Yönetimi",
        importance: "high",
        explanation: "Swap alanı, RAM yetersiz kaldığında diskte kullanılan sanal bellek alanıdır."
    },
    
    // HAFTA 4: İS Katmanları, Çekirdek, Sistem Çağrıları
    { 
        q: "Bir işletim sisteminin yazılım tasarımında ele alınması gereken iki önemli konudan biri Performans, diğeri nedir?", 
        t: "mcq", 
        o: ["Kaynakların özel kullanımı", "Kullanıcı arayüzü", "Fiyat", "Boyut"],
        a: "Kaynakların özel kullanımı",
        difficulty: "medium",
        week: 4,
        topic: "Genel Kavramlar",
        importance: "high",
        explanation: "İşletim sistemi tasarımında iki önemli konu: Performans ve Kaynakların özel kullanımı (yalıtım/koruma)."
    },
    { 
        q: "İşlemcinin, işletim sisteminin kodlarını çalıştırmaya başladığı yetkili moda ne ad verilir?", 
        t: "mcq", 
        o: ["Supervisor Mod", "User Mod", "Kernel Mod", "System Mod"],
        a: "Supervisor Mod",
        difficulty: "medium",
        week: 4,
        topic: "Çekirdek",
        importance: "high",
        explanation: "Supervisor mod (veya kernel mod), işletim sisteminin tüm kaynaklara erişebildiği yetkili çalışma modudur."
    },
    { 
        q: "Kullanıcı modundaki bir işlemin işletim sistemini çağırdığında, işlemcinin hemen supervisor moda geçmesine ne denir?", 
        t: "mcq", 
        o: ["Sistem Çağrısı", "Kesme", "Tuzak", "Hata"],
        a: "Sistem Çağrısı",
        difficulty: "medium",
        week: 4,
        topic: "Sistem Çağrıları",
        importance: "high",
        explanation: "Sistem çağrısı (system call), kullanıcı modundan kernel moduna geçişi sağlar."
    },
    { 
        q: "İşlemcide, bir programın çalışma yeteneğini gösteren bite ne denir?", 
        t: "mcq", 
        o: ["Mod Biti", "Status Biti", "Flag Biti", "Control Biti"],
        a: "Mod Biti",
        difficulty: "medium",
        week: 4,
        topic: "Çekirdek",
        importance: "high",
        explanation: "Mod biti, programın kullanıcı modunda mı yoksa kernel modunda mı çalıştığını belirler."
    },
    { 
        q: "Mod biti (mode bit) hangi değeri aldığında 'supervisor (kernel) mod'da çalışıldığı anlaşılır?", 
        t: "mcq", 
        o: ["0", "1", "2", "3"],
        a: "0",
        difficulty: "medium",
        week: 4,
        topic: "Çekirdek",
        importance: "high",
        explanation: "Mod biti 0 ise supervisor (kernel) modu, 1 ise kullanıcı modudur."
    },
    { 
        q: "İşletim sistemi programları hangi modda çalışır?", 
        t: "mcq", 
        o: ["Supervisor Mod", "User Mod", "Guest Mod", "Safe Mod"],
        a: "Supervisor Mod",
        difficulty: "medium",
        week: 4,
        topic: "Çekirdek",
        importance: "high",
        explanation: "İşletim sistemi programları, tüm kaynaklara erişebilmek için supervisor modda çalışır."
    },
    { 
        q: "İşletim sistemi ve işlemler arasında bir arayüz görevi gören, genellikle Assembly dili komutları şeklinde olan yapı nedir?", 
        t: "mcq", 
        o: ["Sistem Çağrıları", "Kütüphaneler", "Sürücüler", "API"],
        a: "Sistem Çağrıları",
        difficulty: "hard",
        week: 4,
        topic: "Sistem Çağrıları",
        importance: "high",
        explanation: "Sistem çağrıları, işlemler ile işletim sistemi arasında düşük seviyeli arayüz sağlar."
    },
    { 
        q: "Microsoft Windows, sistem çağrılarını hangi API ile gerçekleştirmektedir?", 
        t: "mcq", 
        o: ["Win32 API", "POSIX API", "Java API", ".NET API"],
        a: "Win32 API",
        difficulty: "hard",
        week: 4,
        topic: "Sistem Çağrıları",
        importance: "medium",
        explanation: "Microsoft Windows, sistem çağrılarını Win32 API üzerinden gerçekleştirir."
    },
    { 
        q: "UNIX/Linux sistemlerinde sistem çağrıları hangi dilde yazılmıştır?", 
        t: "mcq", 
        o: ["C", "Assembly", "Java", "Python"],
        a: "C",
        difficulty: "medium",
        week: 4,
        topic: "Sistem Çağrıları",
        importance: "medium",
        explanation: "UNIX/Linux sistem çağrıları genellikle C dili ile yazılmıştır."
    },
    { 
        q: "Dosya okuma/yazma, işlem oluşturma gibi işlemler hangi mekanizma ile yapılır?", 
        t: "mcq", 
        o: ["Sistem Çağrıları", "Kütüphaneler", "Makrolar", "Fonksiyonlar"],
        a: "Sistem Çağrıları",
        difficulty: "medium",
        week: 4,
        topic: "Sistem Çağrıları",
        importance: "high",
        explanation: "Sistem çağrıları, dosya işlemleri, işlem yönetimi gibi işletim sistemi hizmetlerine erişim sağlar."
    },
    { 
        q: "Word, Excel gibi kullanıcı tarafından kullanılan her tür program, işletim sistemi katmanlarının hangi seviyesinde yer alır?", 
        t: "mcq", 
        o: ["Uygulama Katmanı", "Çekirdek Katmanı", "Donanım Katmanı", "Sistem Katmanı"],
        a: "Uygulama Katmanı",
        difficulty: "easy",
        week: 4,
        topic: "Katmanlar",
        importance: "medium",
        explanation: "Uygulama Katmanı, kullanıcıların doğrudan kullandığı programların bulunduğu en üst katmandır."
    },
    { 
        q: "İşletim sisteminin kalbi olarak adlandırılan ve tüm sistem kaynaklarını yöneten katman hangisidir?", 
        t: "mcq", 
        o: ["Çekirdek (Kernel)", "Shell", "GUI", "API"],
        a: "Çekirdek (Kernel)",
        difficulty: "medium",
        week: 4,
        topic: "Çekirdek",
        importance: "high",
        explanation: "Çekirdek (kernel), işletim sisteminin kalbi olarak tüm sistem kaynaklarını yönetir."
    },
    { 
        q: "Aşağıdakilerden hangisi bir çekirdek türü değildir?", 
        t: "mcq", 
        o: ["Supervisor Çekirdek", "Monolitik", "Mikrokernel", "Hibrid Çekirdek"], 
        a: "Supervisor Çekirdek",
        difficulty: "medium",
        week: 4,
        topic: "Çekirdek",
        importance: "medium",
        explanation: "Çekirdek türleri: Monolitik, Mikrokernel ve Hibrid çekirdektir."
    },
    { 
        q: "Tüm yazılımlar ve sürücülerin işletim sistemi çekirdeğinde yer aldığı çekirdek tipine ne denir?", 
        t: "mcq", 
        o: ["Monolitik Çekirdek", "Mikrokernel", "Hibrid Çekirdek", "Nano Çekirdek"],
        a: "Monolitik Çekirdek",
        difficulty: "hard",
        week: 4,
        topic: "Çekirdek",
        importance: "high",
        explanation: "Monolitik çekirdeklerde tüm sistem servisleri çekirdek içindedir. Hızlıdır ama bir hata tüm sistemi etkileyebilir."
    },
    { 
        q: "Unix, ne tür bir çekirdeğe örnektir?", 
        t: "mcq", 
        o: ["Monolitik", "Mikrokernel", "Hibrid", "Nano"],
        a: "Monolitik",
        difficulty: "medium",
        week: 4,
        topic: "Çekirdek",
        importance: "medium",
        explanation: "Unix, monolitik çekirdek yapısına sahip bir işletim sistemidir."
    },
    { 
        q: "Sadece en önemli işletim sistemi fonksiyonlarının bulunduğu küçük boyutlu çekirdeklere ne denir?", 
        t: "mcq", 
        o: ["Mikrokernel", "Monolitik Çekirdek", "Hibrid Çekirdek", "Makrokernel"],
        a: "Mikrokernel",
        difficulty: "hard",
        week: 4,
        topic: "Çekirdek",
        importance: "high",
        explanation: "Mikrokernel (microkernel), sadece temel işletim sistemi fonksiyonlarını içeren minimal çekirdek yapısıdır."
    },
    { 
        q: "Mikrokernellerde, sürücüler ve dosya sistemleri çekirdeğin dışında nasıl çalışır?", 
        t: "mcq", 
        o: ["Kullanıcı seviyesinde", "Kernel seviyesinde", "Donanım seviyesinde", "Firmware seviyesinde"],
        a: "Kullanıcı seviyesinde",
        difficulty: "hard",
        week: 4,
        topic: "Çekirdek",
        importance: "medium",
        explanation: "Mikrokernellerde birçok servis kullanıcı seviyesinde çalışır, bu da daha güvenli ama daha yavaştır."
    },
    { 
        q: "Monolitik ve mikrokernel yapılarının avantajlarını birleştiren çekirdek tipine ne denir?", 
        t: "mcq", 
        o: ["Hibrid Çekirdek", "Super Çekirdek", "Mega Çekirdek", "Dual Çekirdek"],
        a: "Hibrid Çekirdek",
        difficulty: "medium",
        week: 4,
        topic: "Çekirdek",
        importance: "medium",
        explanation: "Hibrid çekirdekler, monolitik ve mikrokernel yaklaşımlarının avantajlarını birleştirir."
    },
];
console.log(`✅ ${window.questionBank.length} soru yüklendi!`);
